Repository juju/juju-gui, pull requests merged in 2018-06, with the labels that each got.

#3674 Fix removed payment method message
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/payment/payment.js
  jujugui/static/gui/src/app/components/deployment-flow/payment/test-payment.js
Labels: QA: Needed, bug

#3678 Update jujulib modules to be importable
  jujugui/static/gui/src/app/assets/javascripts/js-macaroon.js
  jujugui/static/gui/src/app/assets/javascripts/sjcl.js
  jujugui/static/gui/src/app/assets/javascripts/tweetnacl.js
  jujugui/static/gui/src/app/components/deployment-flow/direct-deploy/test-direct-deploy.js
  jujugui/static/gui/src/app/components/entity-details/content/files/test-files.js
  jujugui/static/gui/src/app/components/entity-details/content/resources/test-resources.js
  jujugui/static/gui/src/app/components/icon-list/test-icon-list.js
  jujugui/static/gui/src/app/components/inspector/change-version/item/test-item.js
  jujugui/static/gui/src/app/components/inspector/change-version/test-change-version.js
  jujugui/static/gui/src/app/components/inspector/config/test-config.js
  jujugui/static/gui/src/app/components/inspector/service-overview/test-service-overview.js
  jujugui/static/gui/src/app/components/profile/bundle-list/test-bundle-list.js
  jujugui/static/gui/src/app/components/profile/charm-list/test-charm-list.js
  jujugui/static/gui/src/app/components/search-results/item/test-item.js
  jujugui/static/gui/src/app/components/status/test-status.js
  jujugui/static/gui/src/app/init.js
  jujugui/static/gui/src/app/jujulib/bakery.js
  jujugui/static/gui/src/app/jujulib/bundleservice.js
  jujugui/static/gui/src/app/jujulib/charmstore.js
  jujugui/static/gui/src/app/jujulib/identity.js
  jujugui/static/gui/src/app/jujulib/index.js
  jujugui/static/gui/src/app/jujulib/payment.js
  jujugui/static/gui/src/app/jujulib/plans.js
  jujugui/static/gui/src/app/jujulib/rates.js
  jujugui/static/gui/src/app/jujulib/reconnecting-websocket.js
  jujugui/static/gui/src/app/jujulib/stripe.js
  jujugui/static/gui/src/app/jujulib/terms.js
  jujugui/static/gui/src/app/jujulib/test-bakery.js
  jujugui/static/gui/src/app/jujulib/test-bundleservice.js
  jujugui/static/gui/src/app/jujulib/test-charmstore.js
  jujugui/static/gui/src/app/jujulib/test-identity.js
  jujugui/static/gui/src/app/jujulib/test-payment.js
  jujugui/static/gui/src/app/jujulib/test-plans.js
  jujugui/static/gui/src/app/jujulib/test-rates.js
  jujugui/static/gui/src/app/jujulib/test-stripe.js
  jujugui/static/gui/src/app/jujulib/test-terms.js
  jujugui/static/gui/src/app/jujulib/test-urls.js
  jujugui/static/gui/src/app/jujulib/test-utils.js
  jujugui/static/gui/src/app/jujulib/urls.js
  jujugui/static/gui/src/app/jujulib/utils.js
  jujugui/static/gui/src/app/views/utils.js
  jujugui/static/gui/src/test/test_entity_extension.js
  jujugui/static/gui/src/test/test_env.js
  jujugui/static/gui/src/test/test_env_api.js
  jujugui/static/gui/src/test/test_model.js
  jujugui/static/gui/src/test/test_model_bundle.js
  jujugui/static/gui/src/test/test_model_controller.js
  jujugui/static/gui/src/test/test_model_handlers.js
  jujugui/static/gui/src/test/test_utils.js
  jujugui/templates/index.html.go
  jujugui/templates/index.html.mako
  karma-mocha-old.conf.js.tmpl
  karma.conf.js.tmpl
Labels: QA: OK

#3679 Add ssh to machine button to machineview machines
  Makefile
  jujugui/static/gui/src/app/components/machine-view/machine-view.js
  jujugui/static/gui/src/app/components/machine-view/machine/machine.js
  jujugui/static/gui/src/app/components/machine-view/machine/test-machine.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/state/state.js
  jujugui/static/gui/src/app/state/test-state.js
Labels: QA: OK, Review: Needed

#3683 Fix the go config template
  jujugui/templates/config.js.go
Labels: QA: Needed

#3685 Shell integrations for units
  jujugui/static/gui/src/app/components/inspector/inspector.js
  jujugui/static/gui/src/app/components/inspector/test-inspector.js
  jujugui/static/gui/src/app/components/inspector/unit-details/test-unit-details.js
  jujugui/static/gui/src/app/components/inspector/unit-details/unit-details.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK, feature

#3682 Require YUI modules
  jujugui/static/gui/src/app/extensions/yui-patches.js
  jujugui/static/gui/src/app/init.js
  jujugui/static/gui/src/app/init/test-endpoint-utils.js
  jujugui/static/gui/src/app/init/topology/test-environment.js
  jujugui/static/gui/src/app/models/bundle.js
  jujugui/static/gui/src/app/models/charm.js
  jujugui/static/gui/src/app/models/entity-extension.js
  jujugui/static/gui/src/app/models/handlers.js
  jujugui/static/gui/src/app/models/model-controller.js
  jujugui/static/gui/src/app/models/models.js
  jujugui/static/gui/src/app/store/env/api.js
  jujugui/static/gui/src/app/store/env/base.js
  jujugui/static/gui/src/app/store/env/controller-api.js
  jujugui/static/gui/src/app/test-init.js
  jujugui/static/gui/src/app/utils/environment-change-set.js
  jujugui/static/gui/src/app/views/bundle-import-notifications.js
  jujugui/static/gui/src/app/views/ghost-deployer-extension.js
  jujugui/static/gui/src/app/views/utils.js
  jujugui/static/gui/src/app/yui-modules.js
  jujugui/static/gui/src/test/test_bundle_import_notifications.js
  jujugui/static/gui/src/test/test_controller_api.js
  jujugui/static/gui/src/test/test_entity_extension.js
  jujugui/static/gui/src/test/test_env.js
  jujugui/static/gui/src/test/test_env_api.js
  jujugui/static/gui/src/test/test_env_change_set.js
  jujugui/static/gui/src/test/test_ghost_deployer_extension.js
  jujugui/static/gui/src/test/test_login.js
  jujugui/static/gui/src/test/test_model.js
  jujugui/static/gui/src/test/test_model_bundle.js
  jujugui/static/gui/src/test/test_model_controller.js
  jujugui/static/gui/src/test/test_model_handlers.js
  jujugui/templates/index.html.go
  jujugui/templates/index.html.mako
Labels: QA: OK

#3687 Adds jujushell buttons for the unit in error state
  jujugui/static/gui/src/app/components/inspector/unit-details/test-unit-details.js
  jujugui/static/gui/src/app/components/inspector/unit-details/unit-details.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK

#3686 Require jujulib modules
  jujugui/static/gui/src/app/components/deployment-flow/direct-deploy/direct-deploy.js
  jujugui/static/gui/src/app/components/deployment-flow/direct-deploy/test-direct-deploy.js
  jujugui/static/gui/src/app/components/entity-details/content/files/files.js
  jujugui/static/gui/src/app/components/entity-details/content/files/test-files.js
  jujugui/static/gui/src/app/components/entity-details/content/resources/resources.js
  jujugui/static/gui/src/app/components/entity-details/content/resources/test-resources.js
  jujugui/static/gui/src/app/components/icon-list/icon-list.js
  jujugui/static/gui/src/app/components/icon-list/test-icon-list.js
  jujugui/static/gui/src/app/components/inspector/change-version/change-version.js
  jujugui/static/gui/src/app/components/inspector/change-version/item/test-item.js
  jujugui/static/gui/src/app/components/inspector/change-version/test-change-version.js
  jujugui/static/gui/src/app/components/inspector/config/config.js
  jujugui/static/gui/src/app/components/inspector/config/test-config.js
  jujugui/static/gui/src/app/components/inspector/service-overview/service-overview.js
  jujugui/static/gui/src/app/components/inspector/service-overview/test-service-overview.js
  jujugui/static/gui/src/app/components/profile/bundle-list/bundle-list.js
  jujugui/static/gui/src/app/components/profile/bundle-list/test-bundle-list.js
  jujugui/static/gui/src/app/components/profile/charm-list/charm-list.js
  jujugui/static/gui/src/app/components/profile/charm-list/test-charm-list.js
  jujugui/static/gui/src/app/components/search-results/item/item.js
  jujugui/static/gui/src/app/components/search-results/item/test-item.js
  jujugui/static/gui/src/app/init.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/init/topology/service.js
  jujugui/static/gui/src/app/init/topology/test-environment.js
  jujugui/static/gui/src/app/init/topology/test-service.js
  jujugui/static/gui/src/app/init/utils/bakery-utils.js
  jujugui/static/gui/src/app/init/utils/test-bakery-utils.js
  jujugui/static/gui/src/app/models/charm.js
  jujugui/static/gui/src/app/models/handlers.js
  jujugui/static/gui/src/app/models/models.js
  jujugui/static/gui/src/app/store/env/api.js
  jujugui/static/gui/src/app/store/env/base.js
  jujugui/static/gui/src/app/test-init.js
  jujugui/static/gui/src/app/views/utils.js
  jujugui/static/gui/src/test/factory.js
  jujugui/static/gui/src/test/globalconfig.js
  jujugui/static/gui/src/test/test_entity_extension.js
  jujugui/static/gui/src/test/test_env.js
  jujugui/static/gui/src/test/test_env_api.js
  jujugui/static/gui/src/test/test_model.js
  jujugui/static/gui/src/test/test_model_controller.js
  jujugui/static/gui/src/test/test_model_handlers.js
  jujugui/static/gui/src/test/test_utils.js
  karma-mocha-old.conf.js.tmpl
  karma.conf.js.tmpl
Labels: QA: OK

#3693 Use new jaaslib
  jujugui/static/gui/src/app/components/deployment-flow/direct-deploy/direct-deploy.js
  jujugui/static/gui/src/app/components/entity-details/content/files/files.js
  jujugui/static/gui/src/app/components/entity-details/content/resources/resources.js
  jujugui/static/gui/src/app/components/icon-list/icon-list.js
  jujugui/static/gui/src/app/components/inspector/change-version/change-version.js
  jujugui/static/gui/src/app/components/inspector/change-version/item/test-item.js
  jujugui/static/gui/src/app/components/inspector/change-version/test-change-version.js
  jujugui/static/gui/src/app/components/inspector/config/config.js
  jujugui/static/gui/src/app/components/inspector/service-overview/service-overview.js
  jujugui/static/gui/src/app/components/profile/bundle-list/bundle-list.js
  jujugui/static/gui/src/app/components/profile/charm-list/charm-list.js
  jujugui/static/gui/src/app/components/search-results/item/item.js
  jujugui/static/gui/src/app/components/status/test-status.js
  jujugui/static/gui/src/app/init.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/init/testing-factory.js
  jujugui/static/gui/src/app/init/topology/service.js
  jujugui/static/gui/src/app/init/topology/test-environment.js
  jujugui/static/gui/src/app/init/topology/test-service.js
  jujugui/static/gui/src/app/init/utils.js
  jujugui/static/gui/src/app/init/utils/bakery-utils.js
  jujugui/static/gui/src/app/init/utils/test-bakery-utils.js
  jujugui/static/gui/src/app/jujulib/bakery.js
  jujugui/static/gui/src/app/jujulib/bundleservice.js
  jujugui/static/gui/src/app/jujulib/charmstore.js
  jujugui/static/gui/src/app/jujulib/identity.js
  jujugui/static/gui/src/app/jujulib/index.js
  jujugui/static/gui/src/app/jujulib/payment.js
  jujugui/static/gui/src/app/jujulib/plans.js
  jujugui/static/gui/src/app/jujulib/rates.js
  jujugui/static/gui/src/app/jujulib/stripe.js
  jujugui/static/gui/src/app/jujulib/terms.js
  jujugui/static/gui/src/app/jujulib/test-bakery.js
  jujugui/static/gui/src/app/jujulib/test-bundleservice.js
  jujugui/static/gui/src/app/jujulib/test-charmstore.js
  jujugui/static/gui/src/app/jujulib/test-identity.js
  jujugui/static/gui/src/app/jujulib/test-payment.js
  jujugui/static/gui/src/app/jujulib/test-plans.js
  jujugui/static/gui/src/app/jujulib/test-rates.js
  jujugui/static/gui/src/app/jujulib/test-stripe.js
  jujugui/static/gui/src/app/jujulib/test-terms.js
  jujugui/static/gui/src/app/jujulib/test-urls.js
  jujugui/static/gui/src/app/jujulib/test-utils.js
  jujugui/static/gui/src/app/jujulib/urls.js
  jujugui/static/gui/src/app/jujulib/utils.js
  jujugui/static/gui/src/app/models/charm.js
  jujugui/static/gui/src/app/models/handlers.js
  jujugui/static/gui/src/app/store/env/api.js
  jujugui/static/gui/src/app/test-init.js
  jujugui/static/gui/src/test/test_model_bundle.js
  karma-mocha-old.conf.js.tmpl
  karma.conf.js.tmpl
  package-lock.json
  package.json
Labels: QA: OK

#3694 Remove YUI from the controller module
  jujugui/static/gui/src/app/init.js
  jujugui/static/gui/src/app/models/model-controller.js
  jujugui/static/gui/src/app/models/test-model-controller.js
  jujugui/static/gui/src/app/yui-modules.js
  jujugui/static/gui/src/test/globalconfig.js
  jujugui/templates/index.html.go
  jujugui/templates/index.html.mako
  karma-mocha-old.conf.js.tmpl
  karma.conf.js.tmpl
Labels: QA: OK

#3695 Import urls from jaaslib
  jujugui/static/gui/src/app/components/charmbrowser/charmbrowser.js
  jujugui/static/gui/src/app/components/charmbrowser/test-charmbrowser.js
  jujugui/static/gui/src/app/components/entity-details/entity-details.js
  jujugui/static/gui/src/app/components/entity-details/header/header.js
  jujugui/static/gui/src/app/components/entity-details/header/test-header.js
  jujugui/static/gui/src/app/components/entity-details/test-entity-details.js
  jujugui/static/gui/src/app/components/status/status.js
  jujugui/static/gui/src/app/components/status/test-status.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK

#3701 Remove old test files
  .gitignore
  jujugui/static/gui/src/test/assets/chai.js
  jujugui/static/gui/src/test/data/autocomplete.json
  jujugui/static/gui/src/test/data/blog.yaml
  jujugui/static/gui/src/test/data/browserbundle.json
  jujugui/static/gui/src/test/data/hadoop-api-response.json
  jujugui/static/gui/src/test/data/interesting.json
  jujugui/static/gui/src/test/data/mediawiki-api-response.json
  jujugui/static/gui/src/test/data/memcached-api-response.json
  jujugui/static/gui/src/test/data/mongodb-api-response.json
  jujugui/static/gui/src/test/data/mysql-config.yaml
  jujugui/static/gui/src/test/data/mysql-deployer-mixed.yaml
  jujugui/static/gui/src/test/data/puppet-api-response.json
  jujugui/static/gui/src/test/data/puppetmaster-api-response.json
  jujugui/static/gui/src/test/data/qa.json
  jujugui/static/gui/src/test/data/related.json
  jujugui/static/gui/src/test/data/sample-fakebackend.json
  jujugui/static/gui/src/test/data/search_results.json
  jujugui/static/gui/src/test/data/series_search_results.json
  jujugui/static/gui/src/test/data/wordpress-api-response.json
  jujugui/static/gui/src/test/data/wp-deployer-commas.yaml
  jujugui/static/gui/src/test/data/wp-deployer-nobasket.yaml
  jujugui/static/gui/src/test/data/wp-deployer.yaml
  jujugui/static/gui/src/test/mocha.opts
  jujugui/static/gui/src/test/test_startup.js.bottom
  jujugui/static/gui/src/test/test_startup.js.top
  karma-mocha-old.conf.js.tmpl
Labels: Review: Needed

#3700 Move update annotations to ECS
  jujugui/static/gui/src/app/init/bundle-importer.js
  jujugui/static/gui/src/app/init/environment-change-set.js
  jujugui/static/gui/src/app/init/test-environment-change-set.js
  jujugui/static/gui/src/app/init/topology/topology.js
  jujugui/static/gui/src/app/store/env/api.js
  jujugui/static/gui/src/test/test_env_api.js
Labels: enhancement

#3702 Allow SLA and budget to be selected on deploy
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/support-selection/support-selection.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/support-selection/test-support-selection.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
  jujugui/static/gui/src/app/init.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/init/test-endpoint-utils.js
  jujugui/static/gui/src/app/init/test-utils.js
  jujugui/static/gui/src/app/init/utils.js
  jujugui/static/gui/src/app/store/env/api.js
  jujugui/static/gui/src/app/test-init.js
  jujugui/static/gui/src/test/test_env_api.js
  package-lock.json
  package.json
Labels: QA: OK, feature

#3705 Expert flow cleanups
  jujugui/static/gui/src/app/components/deployment-flow/direct-deploy/_direct-deploy.scss
  jujugui/static/gui/src/app/components/deployment-flow/expert-budget/expert-budget.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-budget/test-expert-budget.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/expert-intro.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/test-expert-intro.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/pricing.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/test-pricing.js
Labels: QA: OK

#3711 Only show ssh buttons under a flag and make terminal state more resilient.
  jujugui/static/gui/src/app/components/inspector/inspector.js
  jujugui/static/gui/src/app/components/inspector/unit-details/unit-details.js
  jujugui/static/gui/src/app/components/machine-view/machine-view.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK, blocker, bug

#3709 Disable mangle to to prevent babili memory leak
  .babelrc
  Makefile
Labels: QA: OK, blocker, bug

#3703 Use shapes for the deployment flow
  jujugui/static/gui/src/app/components/create-payment-user/create-payment-user.js
  jujugui/static/gui/src/app/components/create-payment-user/test-create-payment-user.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/credential.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/test-credential.js
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/payment/payment.js
  jujugui/static/gui/src/app/components/deployment-flow/payment/test-payment.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
  jujugui/static/gui/src/app/components/payment/methods/methods.js
  jujugui/static/gui/src/app/components/payment/methods/test-methods.js
  jujugui/static/gui/src/app/components/payment/payment.js
  jujugui/static/gui/src/app/components/payment/test-payment.js
  jujugui/static/gui/src/app/components/profile/profile.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: Needed

#3704 Fix direct deploy icon race condition
  jujugui/static/gui/src/app/components/deployment-flow/change-item/change-item.js
  jujugui/static/gui/src/app/components/deployment-flow/change-item/test-change-item.js
Labels: QA: OK, bug

#3714 Don't pass createSocketURL for deploy
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/init/test-utils.js
  jujugui/static/gui/src/app/init/utils.js
Labels: QA: OK

#3717 Add package-lock changes.
  package-lock.json
Labels: trivial

#3716 Charmbrowser shapes
  jujugui/static/gui/src/app/components/charmbrowser/charmbrowser.js
  jujugui/static/gui/src/app/components/charmbrowser/test-charmbrowser.js
  jujugui/static/gui/src/app/components/entity-details/content/content.js
  jujugui/static/gui/src/app/components/entity-details/content/test-content.js
  jujugui/static/gui/src/app/components/entity-details/entity-details.js
  jujugui/static/gui/src/app/components/entity-details/test-entity-details.js
  jujugui/static/gui/src/app/components/search-results/search-results.js
  jujugui/static/gui/src/app/components/search-results/test-search-results.js
  jujugui/static/gui/src/app/components/store/store.js
  jujugui/static/gui/src/app/components/store/test-store.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK

#3718 Only use rewire in dev mode
  .babelrc
  Makefile
  package-lock.json
  package.json
Labels: QA: OK, blocker

#3724 Import normalize instead of local asset
  Makefile
  jujugui/static/gui/src/app/assets/css/base.scss
  jujugui/static/gui/src/app/assets/stylesheets/normalize.css
  jujugui/templates/index.html.go
  jujugui/templates/index.html.mako
  package-lock.json
  package.json
Labels: QA: OK

#3723 Remove unused dist files
  MANIFEST.in
  Makefile
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/sshkey/sshkey.js
  jujugui/static/gui/src/app/components/deployment-flow/sshkey/test-sshkey.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
  jujugui/static/gui/src/app/init.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/init/test-bundle-importer.js
  jujugui/static/gui/src/app/init/test-endpoint-utils.js
  jujugui/static/gui/src/app/init/test-environment-change-set.js
  jujugui/static/gui/src/app/init/test-utils.js
  jujugui/static/gui/src/app/init/topology/test-environment.js
  jujugui/static/gui/src/app/models/test-model-controller.js
  jujugui/static/gui/src/app/models/test-models.js
  jujugui/static/gui/src/app/state/state.js
  jujugui/static/gui/src/app/state/test-state.js
  jujugui/static/gui/src/app/test-init.js
  jujugui/static/gui/src/app/user/test-user.js
  jujugui/static/gui/src/app/user/user.js
  jujugui/static/gui/src/app/utils/github-ssh-keys.js
  jujugui/static/gui/src/app/utils/statsd.js
  jujugui/static/gui/src/app/utils/test-github-ssh-keys.js
  jujugui/static/gui/src/app/utils/test-statsd.js
  jujugui/static/gui/src/test/globalconfig.js
  jujugui/static/gui/src/test/test_controller_api.js
  jujugui/static/gui/src/test/test_env.js
  jujugui/static/gui/src/test/test_env_api.js
  jujugui/static/gui/src/test/test_login.js
  jujugui/templates/index.html.go
  jujugui/templates/index.html.mako
  karma-mocha-old.conf.js.tmpl
  karma.conf.js.tmpl
  scripts/generate_modules.py
Labels: QA: OK

#3725 Add inspector shapes
  jujugui/static/gui/src/app/components/inspector/change-version/change-version.js
  jujugui/static/gui/src/app/components/inspector/change-version/test-change-version.js
  jujugui/static/gui/src/app/components/inspector/expose/expose.js
  jujugui/static/gui/src/app/components/inspector/expose/test-expose.js
  jujugui/static/gui/src/app/components/inspector/header/header.js
  jujugui/static/gui/src/app/components/inspector/header/test-header.js
  jujugui/static/gui/src/app/components/inspector/inspector.js
  jujugui/static/gui/src/app/components/inspector/scale-service/scale-service.js
  jujugui/static/gui/src/app/components/inspector/scale-service/test-scale-service.js
  jujugui/static/gui/src/app/components/inspector/test-inspector.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK

#3722 Clean up post deploy linking
  jujugui/static/gui/src/app/components/post-deployment/post-deployment.js
  jujugui/static/gui/src/app/components/post-deployment/test-post-deployment.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK

#3713 Import the hotkeys module
  jujugui/static/gui/src/app/components/modal-shortcuts/modal-shortcuts.js
  jujugui/static/gui/src/app/components/modal-shortcuts/test-modal-shortcuts.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK

#3715 Import marked lib
  jujugui/static/gui/src/app/components/charmbrowser/charmbrowser.js
  jujugui/static/gui/src/app/components/charmbrowser/test-charmbrowser.js
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/direct-deploy/direct-deploy.js
  jujugui/static/gui/src/app/components/deployment-flow/direct-deploy/test-direct-deploy.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/expert-intro.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/test-expert-intro.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
  jujugui/static/gui/src/app/components/entity-details/content/content.js
  jujugui/static/gui/src/app/components/entity-details/content/description/description.js
  jujugui/static/gui/src/app/components/entity-details/content/description/test-description.js
  jujugui/static/gui/src/app/components/entity-details/content/readme/readme.js
  jujugui/static/gui/src/app/components/entity-details/content/readme/test-readme.js
  jujugui/static/gui/src/app/components/entity-details/content/test-content.js
  jujugui/static/gui/src/app/components/entity-details/entity-details.js
  jujugui/static/gui/src/app/components/entity-details/test-entity-details.js
  jujugui/static/gui/src/app/components/post-deployment/post-deployment.js
  jujugui/static/gui/src/app/components/post-deployment/test-post-deployment.js
  jujugui/static/gui/src/app/components/terminal/test-terminal.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/init/topology/test-environment.js
  jujugui/static/gui/src/app/test-init.js
Labels: QA: OK

#3728 Add util shapes to deployment flow
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/machines/machines.js
  jujugui/static/gui/src/app/components/deployment-flow/machines/test-machines.js
  jujugui/static/gui/src/app/components/deployment-flow/services/services.js
  jujugui/static/gui/src/app/components/deployment-flow/services/test-services.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK
