Repository juju/juju-gui, pull requests merged in 2018-10, with the labels that each got.

#3829 Update GUI dependencies.
  CHANGELOG.md
  jujugui/static/gui/src/app/components/shared/basic-table/row/__snapshots__/test-row.js.snap
  karma.conf.js.tmpl
  package-lock.json
  package.json
Labels: QA: OK, devops

#3835 Make status resilient to missing data
  jujugui/static/gui/src/app/components/shared/status/application-list/__snapshots__/test-application-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/application-list/application-list.js
  jujugui/static/gui/src/app/components/shared/status/application-list/test-application-list.js
  jujugui/static/gui/src/app/components/shared/status/machine-list/__snapshots__/test-machine-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/machine-list/machine-list.js
  jujugui/static/gui/src/app/components/shared/status/machine-list/test-machine-list.js
  jujugui/static/gui/src/app/components/shared/status/relation-list/__snapshots__/test-relation-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/relation-list/relation-list.js
  jujugui/static/gui/src/app/components/shared/status/relation-list/test-relation-list.js
  jujugui/static/gui/src/app/components/shared/status/remote-application-list/__snapshots__/test-remote-application-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/remote-application-list/remote-application-list.js
  jujugui/static/gui/src/app/components/shared/status/remote-application-list/test-remote-application-list.js
  jujugui/static/gui/src/app/components/shared/status/unit-list/__snapshots__/test-unit-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/unit-list/test-unit-list.js
  jujugui/static/gui/src/app/components/shared/status/unit-list/unit-list.js
  package-lock.json
Labels: QA: OK

#3840 Fix readme links from Juju core deployed bundles
  CHANGELOG.md
  jujugui/static/gui/src/app/components/added-services-list/label/label.js
  jujugui/static/gui/src/app/components/added-services-list/label/test-label.js
  package-lock.json
Labels: QA: OK, bug

#3831 Upgrade Profile section to Vanilla markup and styling
  CHANGELOG.md
  Makefile
  jujugui/static/gui/src/app/assets/css/_components.scss
  jujugui/static/gui/src/app/assets/svgs/user_16.svg
  jujugui/static/gui/src/app/components/payment/payment.js
  jujugui/static/gui/src/app/components/profile/__snapshots__/test-profile.js.snap
  jujugui/static/gui/src/app/components/profile/_profile.scss
  jujugui/static/gui/src/app/components/profile/bundle-list/__snapshots__/test-bundle-list.js.snap
  jujugui/static/gui/src/app/components/profile/bundle-list/_bundle-list.scss
  jujugui/static/gui/src/app/components/profile/bundle-list/bundle-list.js
  jujugui/static/gui/src/app/components/profile/bundle-list/test-bundle-list.js
  jujugui/static/gui/src/app/components/profile/charm-list/__snapshots__/test-charm-list.js.snap
  jujugui/static/gui/src/app/components/profile/charm-list/_charm-list.scss
  jujugui/static/gui/src/app/components/profile/charm-list/charm-list.js
  jujugui/static/gui/src/app/components/profile/charm-list/test-charm-list.js
  jujugui/static/gui/src/app/components/profile/charmstore-login/charmstore-login.js
  jujugui/static/gui/src/app/components/profile/charmstore-login/test-charmstore-login.js
  jujugui/static/gui/src/app/components/profile/credential-list/__snapshots__/test-credential-list.js.snap
  jujugui/static/gui/src/app/components/profile/credential-list/_credential-list.scss
  jujugui/static/gui/src/app/components/profile/credential-list/credential-list.js
  jujugui/static/gui/src/app/components/profile/credential-list/test-credential-list.js
  jujugui/static/gui/src/app/components/profile/expanded-content/_expanded-content.scss
  jujugui/static/gui/src/app/components/profile/expanded-content/expanded-content.js
  jujugui/static/gui/src/app/components/profile/expanded-content/test-expanded-content.js
  jujugui/static/gui/src/app/components/profile/header/__snapshots__/test-header.js.snap
  jujugui/static/gui/src/app/components/profile/header/_header.scss
  jujugui/static/gui/src/app/components/profile/header/header.js
  jujugui/static/gui/src/app/components/profile/header/test-header.js
  jujugui/static/gui/src/app/components/profile/invoice-list/__snapshots__/test-invoice-list.js.snap
  jujugui/static/gui/src/app/components/profile/invoice-list/_invoice-list.scss
  jujugui/static/gui/src/app/components/profile/invoice-list/invoice-list.js
  jujugui/static/gui/src/app/components/profile/invoice-list/test-invoice-list.js
  jujugui/static/gui/src/app/components/profile/model-list/__snapshots__/test-model-list.js.snap
  jujugui/static/gui/src/app/components/profile/model-list/_model-list.scss
  jujugui/static/gui/src/app/components/profile/model-list/model-list.js
  jujugui/static/gui/src/app/components/profile/model-list/test-model-list.js
  jujugui/static/gui/src/app/components/profile/navigation/__snapshots__/test-navigation.js.snap
  jujugui/static/gui/src/app/components/profile/navigation/_navigation.scss
  jujugui/static/gui/src/app/components/profile/navigation/navigation.js
  jujugui/static/gui/src/app/components/profile/profile.js
  jujugui/static/gui/src/app/components/shared/basic-table/__snapshots__/test-basic-table.js.snap
  jujugui/static/gui/src/app/components/shared/basic-table/_basic-table.scss
  jujugui/static/gui/src/app/components/shared/basic-table/basic-table.js
  jujugui/static/gui/src/app/components/shared/basic-table/cell/__snapshots__/test-cell.js.snap
  jujugui/static/gui/src/app/components/shared/basic-table/cell/cell.js
  jujugui/static/gui/src/app/components/shared/basic-table/cell/test-cell.js
  jujugui/static/gui/src/app/components/shared/basic-table/row/__snapshots__/test-row.js.snap
  jujugui/static/gui/src/app/components/shared/basic-table/row/row.js
Labels: QA: OK

#3845 Fix spacing around credentials action dropdown
  jujugui/static/gui/src/app/components/profile/credential-list/_credential-list.scss
Labels: QA: OK

#3844 Over override styles for destroy model PopUp
  jujugui/static/gui/src/app/components/profile/model-list/_model-list.scss
Labels: QA: OK

#3843 Increase width of owner col in models table
  jujugui/static/gui/src/app/components/profile/model-list/_model-list.scss
Labels: QA: OK

#3847 Fix showing login link on JAAS
  CHANGELOG.md
  jujugui/static/gui/src/app/init/app.js
Labels: QA: OK, bug

#3849 Due to recent changes in React this technique to scroll to an element no longer works.
  jujugui/static/gui/src/app/components/machine-view/machine-view.js
Labels: QA: OK, bug

#3850 Fix the status table styles
  jujugui/static/gui/src/app/components/shared/basic-table/_basic-table.scss
  jujugui/static/gui/src/app/components/shared/basic-table/cell/__snapshots__/test-cell.js.snap
  jujugui/static/gui/src/app/components/shared/basic-table/cell/cell.js
  jujugui/static/gui/src/app/components/shared/basic-table/row/__snapshots__/test-row.js.snap
  jujugui/static/gui/src/app/components/shared/basic-table/row/row.js
  jujugui/static/gui/src/app/components/shared/basic-table/row/test-row.js
  jujugui/static/gui/src/app/components/shared/status/table/_table.scss
  jujugui/static/gui/src/app/components/status/status.js
  jujugui/static/gui/src/app/components/status/test-status.js
Labels: QA: OK, bug

#3854 Fix array replace
  jujugui/static/gui/src/app/maraca/maraca.js
  jujugui/static/gui/src/app/maraca/test-maraca.js
Labels: QA: OK, bug

#3855 Don't display the expert flow if there are no plans
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/__snapshots__/test-expert-intro.js.snap
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/expert-intro.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/test-expert-intro.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
Labels: QA: OK, bug

#3861 Fixed Google Cloud Platform logo anomaly on Firefox
  jujugui/static/gui/src/app/assets/stack/svg/sprite.css.svg
  jujugui/static/gui/src/app/assets/svgs/google.svg
Labels: QA: OK

#3860 Update more tables to use new Vanilla
  jujugui/static/gui/src/app/components/deployment-flow/pricing/plan-table/__snapshots__/test-plan-table.js.snap
  jujugui/static/gui/src/app/components/deployment-flow/pricing/plan-table/_plan-table.scss
  jujugui/static/gui/src/app/components/deployment-flow/pricing/plan-table/plan-table.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/plan-table/test-plan-table.js
  jujugui/static/gui/src/app/components/deployment-flow/services/__snapshots__/test-services.js.snap
  jujugui/static/gui/src/app/components/deployment-flow/services/services.js
  jujugui/static/gui/src/app/components/deployment-flow/services/test-services.js
Labels: QA: OK, bug
