Repository juju/juju-gui, pull requests merged in 2018-05, with the labels that each got.

#3636 Update YUI
  package-lock.json
  package.json
Labels: QA: OK, devops

#3638 Use charm/bundle supplied expert data.
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/expert-intro.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/test-expert-intro.js
  jujugui/static/gui/src/app/jujulib/charmstore.js
  jujugui/static/gui/src/app/jujulib/test-charmstore.js
  jujugui/static/gui/src/app/models/entity-extension.js
  jujugui/static/gui/src/test/test_entity_extension.js
Labels: QA: OK, enhancement

#3639 Store the budget
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-budget/expert-budget.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-budget/test-expert-budget.js
  jujugui/static/gui/src/app/components/generic-input/generic-input.js
Labels: QA: OK, enhancement

#3637 More expert flow improvements
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/expert-intro.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/test-expert-intro.js
  jujugui/static/gui/src/app/components/deployment-flow/model-name/model-name.js
  jujugui/static/gui/src/app/components/deployment-flow/model-name/test-model-name.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/_pricing.scss
  jujugui/static/gui/src/app/components/deployment-flow/pricing/pricing.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/test-pricing.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: Needed, enhancement

#3640 Update xterm
  jujugui/static/gui/src/app/components/terminal/_terminal.scss
  jujugui/static/gui/src/app/components/terminal/terminal.js
  jujugui/static/gui/src/app/components/terminal/test-terminal.js
  jujugui/static/gui/src/app/components/terminal/xterm.scss
  package-lock.json
  package.json
Labels: QA: OK, enhancement

#3645 Update expert name.
  jujugui/static/gui/src/app/components/store/store.js
Labels: QA: OK, bug

#3646 Fix a race generating weird app placement in the canvas
  jujugui/static/gui/src/app/d3-components/test-d3-components.js
  jujugui/static/gui/src/app/init/bundle-importer.js
  jujugui/static/gui/src/app/init/test-bundle-importer.js
  jujugui/static/gui/src/app/models/handlers.js
  jujugui/static/gui/src/test/test_model_handlers.js
Labels: QA: OK

#3647 Only get a new dd entity if the id changes in the deployment flow.
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
Labels: QA: OK, bug

#3649 Remove humanize timestamp util
  jujugui/static/gui/src/app/components/env-switcher/env-switcher.js
  jujugui/static/gui/src/app/components/env-switcher/list/list.js
  jujugui/static/gui/src/app/components/env-switcher/list/test-list.js
  jujugui/static/gui/src/app/components/env-switcher/test-env-switcher.js
  jujugui/static/gui/src/app/components/header-breadcrumb/header-breadcrumb.js
  jujugui/static/gui/src/app/components/header-breadcrumb/test-header-breadcrumb.js
  jujugui/static/gui/src/app/components/sharing/sharing.js
  jujugui/static/gui/src/app/components/sharing/test-sharing.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/init/test-utils.js
  jujugui/static/gui/src/app/init/utils.js
Labels: QA: OK, devops

#3650 Remove compare semver util
  jujugui/static/gui/src/app/components/inspector/inspector.js
  jujugui/static/gui/src/app/components/inspector/service-overview/service-overview.js
  jujugui/static/gui/src/app/components/inspector/service-overview/test-service-overview.js
  jujugui/static/gui/src/app/components/inspector/test-inspector.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/init/test-utils.js
  jujugui/static/gui/src/app/init/utils.js
Labels: devops

#3653 Directly import pluralize
  jujugui/static/gui/src/app/components/charmbrowser/charmbrowser.js
  jujugui/static/gui/src/app/components/charmbrowser/test-charmbrowser.js
  jujugui/static/gui/src/app/components/date-display/date-display.js
  jujugui/static/gui/src/app/components/entity-details/content/content.js
  jujugui/static/gui/src/app/components/entity-details/content/files/files.js
  jujugui/static/gui/src/app/components/entity-details/content/files/test-files.js
  jujugui/static/gui/src/app/components/entity-details/content/resources/resources.js
  jujugui/static/gui/src/app/components/entity-details/content/resources/test-resources.js
  jujugui/static/gui/src/app/components/entity-details/content/test-content.js
  jujugui/static/gui/src/app/components/entity-details/entity-details.js
  jujugui/static/gui/src/app/components/entity-details/header/header.js
  jujugui/static/gui/src/app/components/entity-details/header/test-header.js
  jujugui/static/gui/src/app/components/entity-details/test-entity-details.js
  jujugui/static/gui/src/app/components/env-size-display/env-size-display.js
  jujugui/static/gui/src/app/components/env-size-display/test-env-size-display.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK, devops

#3655 Import validateForm util
  jujugui/static/gui/src/app/components/address-form/address-form.js
  jujugui/static/gui/src/app/components/address-form/test-address-form.js
  jujugui/static/gui/src/app/components/card-form/card-form.js
  jujugui/static/gui/src/app/components/card-form/test-card-form.js
  jujugui/static/gui/src/app/components/create-payment-user/create-payment-user.js
  jujugui/static/gui/src/app/components/create-payment-user/test-create-payment-user.js
  jujugui/static/gui/src/app/components/credential-add-edit/credential-add-edit.js
  jujugui/static/gui/src/app/components/credential-add-edit/test-credential-add-edit.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/add/add.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/add/test-add.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/credential.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/test-credential.js
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/payment/payment.js
  jujugui/static/gui/src/app/components/deployment-flow/payment/test-payment.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
  jujugui/static/gui/src/app/components/payment/details/address/address.js
  jujugui/static/gui/src/app/components/payment/details/address/test-address.js
  jujugui/static/gui/src/app/components/payment/details/details.js
  jujugui/static/gui/src/app/components/payment/details/test-details.js
  jujugui/static/gui/src/app/components/payment/methods/method/method.js
  jujugui/static/gui/src/app/components/payment/methods/method/test-method.js
  jujugui/static/gui/src/app/components/payment/methods/methods.js
  jujugui/static/gui/src/app/components/payment/methods/test-methods.js
  jujugui/static/gui/src/app/components/payment/payment.js
  jujugui/static/gui/src/app/components/payment/test-payment.js
  jujugui/static/gui/src/app/components/profile/credential-list/credential-list.js
  jujugui/static/gui/src/app/components/profile/credential-list/test-credential-list.js
  jujugui/static/gui/src/app/components/profile/profile.js
  jujugui/static/gui/src/app/components/profile/test-profile.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK, devops

#3656 Make root state parsing less restrictive.
  jujugui/static/gui/src/app/state/state.js
  jujugui/static/gui/src/app/state/test-state.js
Labels: QA: OK, enhancement

#3648 Replace linkify util
  jujugui/static/gui/src/app/components/inspector/config/config.js
  jujugui/static/gui/src/app/components/inspector/config/test-config.js
  jujugui/static/gui/src/app/components/inspector/inspector.js
  jujugui/static/gui/src/app/components/inspector/test-inspector.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK, devops

#3657 Fix cascading plans lookup
  jujugui/static/gui/src/app/components/deployment-flow/pricing/plan-table/plan-table.js
Labels: QA: OK, bug

#3658 Fix direct deploy loading
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
Labels: QA: OK, bug

#3661 Remove unused clear state util
  jujugui/static/gui/src/app/components/inspector/inspector.js
  jujugui/static/gui/src/app/components/inspector/service-overview/service-overview.js
  jujugui/static/gui/src/app/components/inspector/service-overview/test-service-overview.js
  jujugui/static/gui/src/app/components/inspector/test-inspector.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/init/utils.js
Labels: devops

#3660 Import the getName util
  jujugui/static/gui/src/app/components/charmbrowser/charmbrowser.js
  jujugui/static/gui/src/app/components/charmbrowser/test-charmbrowser.js
  jujugui/static/gui/src/app/components/search-results/search-results.js
  jujugui/static/gui/src/app/components/search-results/test-search-results.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK, devops

#3663 Import the getUnitStatusCounts util
  jujugui/static/gui/src/app/components/added-services-list/added-services-list.js
  jujugui/static/gui/src/app/components/added-services-list/item/item.js
  jujugui/static/gui/src/app/components/added-services-list/item/test-item.js
  jujugui/static/gui/src/app/components/added-services-list/test-added-services-list.js
  jujugui/static/gui/src/app/components/inspector/inspector.js
  jujugui/static/gui/src/app/components/inspector/service-overview/service-overview.js
  jujugui/static/gui/src/app/components/inspector/service-overview/test-service-overview.js
  jujugui/static/gui/src/app/components/inspector/test-inspector.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK, devops

#3665 Import the getCloudProviderDetails util
  jujugui/static/gui/src/app/components/credential-add-edit/credential-add-edit.js
  jujugui/static/gui/src/app/components/credential-add-edit/test-credential-add-edit.js
  jujugui/static/gui/src/app/components/deployment-flow/cloud/cloud.js
  jujugui/static/gui/src/app/components/deployment-flow/cloud/test-cloud.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/add/add.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/add/test-add.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/credential.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/test-credential.js
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
  jujugui/static/gui/src/app/components/profile/credential-list/credential-list.js
  jujugui/static/gui/src/app/components/profile/credential-list/test-credential-list.js
  jujugui/static/gui/src/app/components/profile/profile.js
  jujugui/static/gui/src/app/components/profile/test-profile.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: Needed, Review: Needed

#3662 Detect and support the bakeryEnabled config flag
  jujugui/static/gui/src/app/components/login/login.js
  jujugui/static/gui/src/app/components/login/test-login.js
  jujugui/static/gui/src/app/init.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/templates/config.js.go
Labels: QA: Needed, enhancement

#3668 Import changes utils
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/services/services.js
  jujugui/static/gui/src/app/components/deployment-flow/services/test-services.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK

#3669 Show the estimate and calculate basic budget
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-budget/expert-budget.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-budget/test-expert-budget.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/expert-intro.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/test-expert-intro.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/pricing.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/support-selection/plan/plan.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/support-selection/plan/test-plan.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/support-selection/support-selection.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/support-selection/test-support-selection.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/test-pricing.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
  jujugui/static/gui/src/app/models/bundle.js
  jujugui/static/gui/src/app/models/charm.js
Labels: enhancement

#3671 Import the makeEntityModel util
  jujugui/static/gui/src/app/components/charmbrowser/charmbrowser.js
  jujugui/static/gui/src/app/components/charmbrowser/test-charmbrowser.js
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
  jujugui/static/gui/src/app/components/entity-details/entity-details.js
  jujugui/static/gui/src/app/components/entity-details/test-entity-details.js
  jujugui/static/gui/src/app/components/post-deployment/post-deployment.js
  jujugui/static/gui/src/app/components/post-deployment/test-post-deployment.js
  jujugui/static/gui/src/app/components/search-results/search-results.js
  jujugui/static/gui/src/app/components/search-results/test-search-results.js
  jujugui/static/gui/src/app/init.js
  jujugui/static/gui/src/app/init/bundle-importer.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/init/test-bundle-importer.js
Labels: QA: OK

#3666 Import getYAMLConfig util
  .babelrc
  jujugui/static/gui/src/app/components/inspector/config/config.js
  jujugui/static/gui/src/app/components/inspector/config/test-config.js
  jujugui/static/gui/src/app/components/inspector/inspector.js
  jujugui/static/gui/src/app/components/inspector/test-inspector.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/init/test-zip-utils.js
  jujugui/static/gui/src/app/init/topology/test-relation.js
  package-lock.json
  package.json
Labels: QA: OK

#3672 Expert flow terms
  jujugui/static/gui/src/app/assets/css/_components.scss
  jujugui/static/gui/src/app/components/deployment-flow/agreements/_agreements.scss
  jujugui/static/gui/src/app/components/deployment-flow/agreements/agreements.js
  jujugui/static/gui/src/app/components/deployment-flow/agreements/test-agreements.js
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
Labels: QA: OK, enhancement
