Repository juju/juju-gui, pull requests merged in 2018-03, with the labels that each got.

#3562 Disconnect from the current model when destroying it
  jujugui/static/gui/src/app/components/profile/model-list/model-list.js
  jujugui/static/gui/src/app/components/profile/model-list/test-model-list.js
  jujugui/static/gui/src/app/components/profile/profile.js
  jujugui/static/gui/src/app/components/profile/test-profile.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/init/test-utils.js
  jujugui/static/gui/src/app/init/utils.js
Labels: QA: OK, enhancement

#3559 Don't re-assign object variables when adding machines.
  jujugui/static/gui/src/app/init/autodeploy.js
Labels: QA: Needed, bug

#3570 Add expert cards to the entity details
  jujugui/static/gui/src/app/assets/css/_components.scss
  jujugui/static/gui/src/app/assets/images/non-sprites/experts/spicule.png
  jujugui/static/gui/src/app/assets/stack/svg/sprite.css.svg
  jujugui/static/gui/src/app/assets/svgs/bullet.svg
  jujugui/static/gui/src/app/assets/svgs/email.svg
  jujugui/static/gui/src/app/assets/svgs/phone.svg
  jujugui/static/gui/src/app/assets/svgs/web.svg
  jujugui/static/gui/src/app/components/charmbrowser/charmbrowser.js
  jujugui/static/gui/src/app/components/charmbrowser/test-charmbrowser.js
  jujugui/static/gui/src/app/components/entity-details/content/content.js
  jujugui/static/gui/src/app/components/entity-details/content/test-content.js
  jujugui/static/gui/src/app/components/entity-details/entity-details.js
  jujugui/static/gui/src/app/components/entity-details/test-entity-details.js
  jujugui/static/gui/src/app/components/expert-card/_expert-card.scss
  jujugui/static/gui/src/app/components/expert-card/expert-card.js
  jujugui/static/gui/src/app/components/expert-card/test-expert-card.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: enhancement

#3571 Send analytics when the expert contact button is clicked
  jujugui/static/gui/src/app/components/charmbrowser/charmbrowser.js
  jujugui/static/gui/src/app/components/charmbrowser/test-charmbrowser.js
  jujugui/static/gui/src/app/components/entity-details/content/content.js
  jujugui/static/gui/src/app/components/entity-details/content/test-content.js
  jujugui/static/gui/src/app/components/entity-details/entity-details.js
  jujugui/static/gui/src/app/components/entity-details/test-entity-details.js
  jujugui/static/gui/src/app/components/expert-card/expert-card.js
  jujugui/static/gui/src/app/components/expert-card/test-expert-card.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: enhancement

#3568 Merge dropdowns
  jujugui/static/gui/src/app/assets/css/_components.scss
  jujugui/static/gui/src/app/assets/css/_mobile.scss
  jujugui/static/gui/src/app/assets/css/base.scss
  jujugui/static/gui/src/app/components/button-dropdown/_button-dropdown.scss
  jujugui/static/gui/src/app/components/button-dropdown/button-dropdown.js
  jujugui/static/gui/src/app/components/button-dropdown/test-button-dropdown.js
  jujugui/static/gui/src/app/components/dropdown-menu/_dropdown-menu.scss
  jujugui/static/gui/src/app/components/machine-view/header/_header.scss
  jujugui/static/gui/src/app/components/machine-view/header/header.js
  jujugui/static/gui/src/app/components/machine-view/header/test-header.js
  jujugui/static/gui/src/app/components/machine-view/machine-unit/machine-unit.js
  jujugui/static/gui/src/app/components/machine-view/machine-unit/test-machine-unit.js
  jujugui/static/gui/src/app/components/machine-view/machine/_machine.scss
  jujugui/static/gui/src/app/components/machine-view/machine/machine.js
  jujugui/static/gui/src/app/components/machine-view/machine/test-machine.js
  jujugui/static/gui/src/app/components/machine-view/unplaced-unit/_unplaced-unit.scss
  jujugui/static/gui/src/app/components/machine-view/unplaced-unit/test-unplaced-unit.js
  jujugui/static/gui/src/app/components/machine-view/unplaced-unit/unplaced-unit.js
  jujugui/static/gui/src/app/components/more-menu/_more-menu.scss
  jujugui/static/gui/src/app/components/more-menu/more-menu.js
  jujugui/static/gui/src/app/components/more-menu/test-more-menu.js
  jujugui/static/gui/src/app/components/profile/credential-list/_credential-list.scss
  jujugui/static/gui/src/app/components/profile/credential-list/credential-list.js
  jujugui/static/gui/src/app/components/profile/credential-list/test-credential-list.js
  jujugui/static/gui/src/app/components/user-menu/_user-menu.scss
  jujugui/static/gui/src/app/components/user-menu/test-user-menu.js
  jujugui/static/gui/src/app/components/user-menu/user-menu.js
Labels: enhancement

#3573 Add expert card to the store
  jujugui/static/gui/src/app/assets/css/_components.scss
  jujugui/static/gui/src/app/components/entity-details/content/content.js
  jujugui/static/gui/src/app/components/entity-details/content/test-content.js
  jujugui/static/gui/src/app/components/expert-card/_expert-card.scss
  jujugui/static/gui/src/app/components/expert-card/expert-card.js
  jujugui/static/gui/src/app/components/expert-card/experts.js
  jujugui/static/gui/src/app/components/expert-card/test-expert-card.js
  jujugui/static/gui/src/app/components/expert-contact-card/_expert-contact-card.scss
  jujugui/static/gui/src/app/components/expert-contact-card/expert-contact-card.js
  jujugui/static/gui/src/app/components/expert-contact-card/test-expert-contact-card.js
  jujugui/static/gui/src/app/components/expert-store-card/_expert-store-card.scss
  jujugui/static/gui/src/app/components/expert-store-card/expert-store-card.js
  jujugui/static/gui/src/app/components/expert-store-card/test-expert-store-card.js
  jujugui/static/gui/src/app/components/store/store.js
  jujugui/static/gui/src/app/components/store/test-store.js
Labels: enhancement

#3575 Destroy the correct service from the inspector
  jujugui/static/gui/src/app/components/inspector/inspector.js
Labels: QA: OK, bug

#3574 Remove apps' relations store
  jujugui/static/gui/src/app/init/test-utils.js
  jujugui/static/gui/src/app/init/utils.js
  jujugui/static/gui/src/app/models/models.js
  jujugui/static/gui/src/app/utils/environment-change-set.js
  jujugui/static/gui/src/test/test_model.js
Labels: QA: OK, bug

#3576 Add enzyme
  jujugui/static/gui/src/app/components/env-switcher/list/test-list.js
  jujugui/static/gui/src/test/chai-setup.js
  jujugui/static/gui/src/test/enzyme-setup.js
  karma.conf.js.tmpl
  package-lock.json
  package.json
Labels: devops

#3564 Sort profile bundle/charm lists by name
  jujugui/static/gui/src/app/components/profile/bundle-list/bundle-list.js
  jujugui/static/gui/src/app/components/profile/bundle-list/test-bundle-list.js
  jujugui/static/gui/src/app/components/profile/charm-list/charm-list.js
  jujugui/static/gui/src/app/components/profile/charm-list/test-charm-list.js
  jujugui/static/gui/src/app/components/profile/expanded-content/expanded-content.js
Labels: QA: OK, enhancement

#3549 Profile header tooltips
  jujugui/static/gui/src/app/components/profile/header/_header.scss
  jujugui/static/gui/src/app/components/profile/header/header.js
  jujugui/static/gui/src/app/components/profile/header/test-header.js
Labels: QA: OK, enhancement

#3579 Update some tests to enzyme
  jujugui/static/gui/src/app/components/accordion-section/accordion-section.js
  jujugui/static/gui/src/app/components/accordion-section/test-accordion-section.js
  jujugui/static/gui/src/app/components/added-services-list/added-services-list.js
  jujugui/static/gui/src/app/components/added-services-list/item/test-item.js
  jujugui/static/gui/src/app/components/added-services-list/test-added-services-list.js
  jujugui/static/gui/src/app/components/address-form/test-address-form.js
  jujugui/static/gui/src/app/components/env-switcher/list/test-list.js
  jujugui/static/gui/src/app/components/env-switcher/test-env-switcher.js
Labels: Review: Needed, devops

#3581 Update more enzyme tests
  jujugui/static/gui/src/app/components/basic-table/test-basic-table.js
  jujugui/static/gui/src/app/components/boolean-config/test-boolean-config.js
  jujugui/static/gui/src/app/components/budget-chart/test-budget-chart.js
  jujugui/static/gui/src/app/components/budget-table/row/row.js
  jujugui/static/gui/src/app/components/budget-table/row/test-row.js
  jujugui/static/gui/src/app/components/budget-table/test-budget-table.js
  jujugui/static/gui/src/test/chai-setup.js
Labels: devops

#3582 Update even more enzyme tests
  jujugui/static/gui/src/app/components/button-dropdown/test-button-dropdown.js
  jujugui/static/gui/src/app/components/button-row/test-button-row.js
  jujugui/static/gui/src/app/components/card-form/test-card-form.js
  jujugui/static/gui/src/app/components/charmbrowser/charmbrowser.js
  jujugui/static/gui/src/app/components/charmbrowser/test-charmbrowser.js
  jujugui/static/gui/src/app/components/check-list-item/test-check-list-item.js
  jujugui/static/gui/src/app/components/constraints/test-constraints.js
Labels: devops

#3583 Show controller model in model dropdown list
  jujugui/static/gui/src/app/components/env-switcher/env-switcher.js
  jujugui/static/gui/src/app/components/env-switcher/list/list.js
  jujugui/static/gui/src/app/components/env-switcher/list/test-list.js
  jujugui/static/gui/src/app/components/profile/model-list/model-list.js
  jujugui/static/gui/src/app/components/profile/model-list/test-model-list.js
Labels: QA: OK, enhancement

#3585 More enzyme test updates
  jujugui/static/gui/src/app/components/copy-to-clipboard/test-copy-to-clipboard.js
  jujugui/static/gui/src/app/components/create-model-button/test-create-model-button.js
  jujugui/static/gui/src/app/components/create-payment-user/create-payment-user.js
  jujugui/static/gui/src/app/components/create-payment-user/test-create-payment-user.js
  jujugui/static/gui/src/app/components/credential-add-edit/test-credential-add-edit.js
  jujugui/static/gui/src/app/components/date-display/test-date-display.js
  jujugui/static/gui/src/app/components/deployment-bar/notification/notification.js
  jujugui/static/gui/src/app/components/deployment-bar/notification/test-notification.js
  jujugui/static/gui/src/app/components/deployment-bar/test-deployment-bar.js
Labels: devops

#3587 Update credentials tests to use enzyme
  jujugui/static/gui/src/app/components/deployment-flow/credential/credential.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/test-credential.js
Labels: devops

#3586 Update deployment flow tests to enzyme
  jujugui/static/gui/src/app/components/deployment-flow/budget/budget.js
  jujugui/static/gui/src/app/components/deployment-flow/budget/test-budget.js
  jujugui/static/gui/src/app/components/deployment-flow/change-item/test-change-item.js
  jujugui/static/gui/src/app/components/deployment-flow/cloud/test-cloud.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/add/add.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/add/test-add.js
Labels: devops

#3590 Fixed elk-stack link in the store
  jujugui/static/gui/src/app/components/store/store.js
Labels: QA: OK, bug

#3593 Oh no, more enzyme updates
  jujugui/static/gui/src/app/components/env-size-display/test-env-size-display.js
  jujugui/static/gui/src/app/components/expanding-progress/test-expanding-progress.js
  jujugui/static/gui/src/app/components/expanding-row/test-expanding-row.js
  jujugui/static/gui/src/app/components/expert-card/test-expert-card.js
  jujugui/static/gui/src/app/components/expert-contact-card/test-expert-contact-card.js
  jujugui/static/gui/src/app/components/expert-store-card/test-expert-store-card.js
  jujugui/static/gui/src/app/components/file-field/test-file-field.js
  jujugui/static/gui/src/app/components/generic-button/test-generic-button.js
  jujugui/static/gui/src/app/components/generic-input/test-generic-input.js
Labels: devops

#3592 Update remaining entity details tests to use Enzyme
  jujugui/static/gui/src/app/components/entity-details/content/content.js
  jujugui/static/gui/src/app/components/entity-details/content/test-content.js
  jujugui/static/gui/src/app/components/entity-details/header/header.js
  jujugui/static/gui/src/app/components/entity-details/header/test-header.js
  jujugui/static/gui/src/app/components/entity-details/test-entity-details.js
Labels: devops

#3589 Update entity details components to use Enzyme
  jujugui/static/gui/src/app/components/dropdown-menu/test-dropdown-menu.js
  jujugui/static/gui/src/app/components/entity-details/content/config-option/test-config-option.js
  jujugui/static/gui/src/app/components/entity-details/content/description/test-description.js
  jujugui/static/gui/src/app/components/entity-details/content/diagram/test-diagram.js
  jujugui/static/gui/src/app/components/entity-details/content/files/files.js
  jujugui/static/gui/src/app/components/entity-details/content/files/test-files.js
  jujugui/static/gui/src/app/components/entity-details/content/readme/test-readme.js
  jujugui/static/gui/src/app/components/entity-details/content/relations/test-relations.js
  jujugui/static/gui/src/app/components/entity-details/content/resources/test-resources.js
Labels: devops

#3588 Update remaining deployment flow tests to use Enzyme
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/direct-deploy/direct-deploy.js
  jujugui/static/gui/src/app/components/deployment-flow/direct-deploy/test-direct-deploy.js
  jujugui/static/gui/src/app/components/deployment-flow/login/login.js
  jujugui/static/gui/src/app/components/deployment-flow/login/test-login.js
  jujugui/static/gui/src/app/components/deployment-flow/machines/test-machines.js
  jujugui/static/gui/src/app/components/deployment-flow/model-name/test-model-name.js
  jujugui/static/gui/src/app/components/deployment-flow/panel/test-panel.js
  jujugui/static/gui/src/app/components/deployment-flow/payment/test-payment.js
  jujugui/static/gui/src/app/components/deployment-flow/section/test-section.js
  jujugui/static/gui/src/app/components/deployment-flow/services/services.js
  jujugui/static/gui/src/app/components/deployment-flow/services/test-services.js
  jujugui/static/gui/src/app/components/deployment-flow/signup/test-signup.js
  jujugui/static/gui/src/app/components/deployment-flow/sshkey/sshkey.js
  jujugui/static/gui/src/app/components/deployment-flow/sshkey/test-sshkey.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/vpc/test-vpc.js
Labels: devops

#3595 Workaround cpu-cores bug in juju-core
  jujugui/static/gui/src/app/store/env/api.js
  jujugui/static/gui/src/test/test_env_api.js
Labels: QA: OK, bug

#3596 Enzyme is my life
  jujugui/static/gui/src/app/components/hash-link/test-hash-link.js
  jujugui/static/gui/src/app/components/header-breadcrumb/test-header-breadcrumb.js
  jujugui/static/gui/src/app/components/header-logo/test-header-logo.js
  jujugui/static/gui/src/app/components/header-search/test-header-search.js
  jujugui/static/gui/src/app/components/help/help.js
  jujugui/static/gui/src/app/components/help/test-help.js
  jujugui/static/gui/src/app/components/help/tour/test-tour.js
  jujugui/static/gui/src/app/components/icon-list/test-icon-list.js
  jujugui/static/gui/src/app/components/inset-select/test-inset-select.js
Labels: devops

#3597 Start updating inspector tests to use Enzyme
  jujugui/static/gui/src/app/components/inspector/change-version/item/test-item.js
  jujugui/static/gui/src/app/components/inspector/change-version/test-change-version.js
  jujugui/static/gui/src/app/components/inspector/config/test-config.js
  jujugui/static/gui/src/test/required-props.js
Labels: devops

#3591 Fix feature store items in GiJ
  jujugui/static/gui/src/app/assets/images/store/jenkins-promo.png
  jujugui/static/gui/src/app/assets/images/store/kabana-promo.png
  jujugui/static/gui/src/app/assets/images/store/squid-promo.svg
  jujugui/static/gui/src/app/components/store/_store.scss
  jujugui/static/gui/src/app/components/store/store.js
  jujugui/static/gui/src/app/components/store/test-store.js
Labels: QA: OK, bug

#3598 Update payment tests to use Enzyme
  jujugui/static/gui/src/app/components/payment/charges/receipt-popup/test-receipt-popup.js
  jujugui/static/gui/src/app/components/payment/charges/test-charges.js
  jujugui/static/gui/src/app/components/payment/details/address/address.js
  jujugui/static/gui/src/app/components/payment/details/address/test-address.js
  jujugui/static/gui/src/app/components/payment/details/test-details.js
  jujugui/static/gui/src/app/components/payment/methods/card/test-card.js
  jujugui/static/gui/src/app/components/payment/methods/method/test-method.js
  jujugui/static/gui/src/app/components/payment/methods/test-methods.js
  jujugui/static/gui/src/app/components/payment/test-payment.js
Labels: devops

#3600 Improve handling of unknown charm series and add bionic
  jujugui/static/gui/src/app/components/icon-list/icon-list.js
  jujugui/static/gui/src/app/components/icon-list/test-icon-list.js
  jujugui/static/gui/src/app/jujulib/urls.js
  jujugui/static/gui/src/test/required-props.js
Labels: bug, critical

#3599 More inspector enzyme tests
  jujugui/static/gui/src/app/components/inspector/confirm/test-confirm.js
  jujugui/static/gui/src/app/components/inspector/expose/test-expose.js
  jujugui/static/gui/src/app/components/inspector/expose/unit/test-unit.js
  jujugui/static/gui/src/app/components/inspector/header/test-header.js
  jujugui/static/gui/src/app/components/inspector/overview-action/test-overview-action.js
  jujugui/static/gui/src/app/components/inspector/plan/test-plan.js
  jujugui/static/gui/src/app/components/inspector/relate-to/endpoint/test-endpoint.js
  jujugui/static/gui/src/app/components/inspector/relate-to/test-relate-to.js
  jujugui/static/gui/src/app/components/inspector/relations/details/test-details.js
  jujugui/static/gui/src/app/components/inspector/relations/test-relations.js
  jujugui/static/gui/src/app/components/inspector/resources/list/test-list.js
  jujugui/static/gui/src/app/components/inspector/scale-service/test-scale-service.js
Labels: devops

#3603 Update remaining inspector tests to use Enzyme
  jujugui/static/gui/src/app/components/inspector/service-overview/test-service-overview.js
  jujugui/static/gui/src/app/components/inspector/test-inspector.js
  jujugui/static/gui/src/app/components/inspector/unit-details/test-unit-details.js
  jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js
Labels: devops

#3604 More Enzymeing
  jujugui/static/gui/src/app/components/isv-profile/test-isv-profile.js
  jujugui/static/gui/src/app/components/lightbox/test-lightbox.js
  jujugui/static/gui/src/app/components/link/link.js
  jujugui/static/gui/src/app/components/link/test-link.js
  jujugui/static/gui/src/app/components/local-inspector/local-inspector.js
  jujugui/static/gui/src/app/components/local-inspector/test-local-inspector.js
  jujugui/static/gui/src/app/components/login/test-login.js
  jujugui/static/gui/src/app/components/logout/test-logout.js
Labels: devops

#3605 Machine view enzyme tests
  jujugui/static/gui/src/app/components/machine-view/add-machine/test-add-machine.js
  jujugui/static/gui/src/app/components/machine-view/column/test-column.js
  jujugui/static/gui/src/app/components/machine-view/header/test-header.js
  jujugui/static/gui/src/app/components/machine-view/machine-unit/test-machine-unit.js
  jujugui/static/gui/src/app/components/machine-view/machine/test-machine.js
  jujugui/static/gui/src/app/components/machine-view/scale-up/test-scale-up.js
  jujugui/static/gui/src/app/components/machine-view/test-machine-view.js
  jujugui/static/gui/src/app/components/machine-view/unplaced-unit/test-unplaced-unit.js
Labels: devops

#3606 Friday arvo Enzyme updates
  jujugui/static/gui/src/app/components/modal-gui-settings/test-modal-gui-settings.js
  jujugui/static/gui/src/app/components/modal-shortcuts/test-modal-shortcuts.js
  jujugui/static/gui/src/app/components/model-actions/_model-actions.scss
  jujugui/static/gui/src/app/components/model-actions/model-actions.js
  jujugui/static/gui/src/app/components/model-actions/test-model-actions.js
  jujugui/static/gui/src/app/components/notification-list/item/test-item.js
  jujugui/static/gui/src/app/components/notification-list/test-notification-list.js
  jujugui/static/gui/src/app/components/notification/test-notification.js
  jujugui/static/gui/src/app/components/panel/test-panel.js
  jujugui/static/gui/src/app/components/popup/test-popup.js
  jujugui/static/gui/src/app/components/post-deployment/test-post-deployment.js
Labels: devops

#3607 Update profile test to use Enzyme
  jujugui/static/gui/src/app/components/profile/bundle-list/bundle-list.js
  jujugui/static/gui/src/app/components/profile/bundle-list/test-bundle-list.js
  jujugui/static/gui/src/app/components/profile/charm-list/charm-list.js
  jujugui/static/gui/src/app/components/profile/charm-list/test-charm-list.js
  jujugui/static/gui/src/app/components/profile/charmstore-login/test-charmstore-login.js
  jujugui/static/gui/src/app/components/profile/credential-list/credential-list.js
  jujugui/static/gui/src/app/components/profile/credential-list/delete/delete.js
  jujugui/static/gui/src/app/components/profile/credential-list/delete/test-delete.js
  jujugui/static/gui/src/app/components/profile/credential-list/test-credential-list.js
  jujugui/static/gui/src/app/components/profile/expanded-content/test-expanded-content.js
  jujugui/static/gui/src/app/components/profile/header/test-header.js
  jujugui/static/gui/src/app/components/profile/invoice-list/test-invoice-list.js
  jujugui/static/gui/src/app/components/profile/model-list/test-model-list.js
  jujugui/static/gui/src/app/components/profile/navigation/test-navigation.js
  jujugui/static/gui/src/app/components/profile/profile.js
  jujugui/static/gui/src/app/components/profile/test-profile.js
Labels: devops

#3608 Update search results tests to use Enzyme
  jujugui/static/gui/src/app/components/search-results/item/test-item.js
  jujugui/static/gui/src/app/components/search-results/search-results.js
  jujugui/static/gui/src/app/components/search-results/select-filter/test-select-filter.js
  jujugui/static/gui/src/app/components/search-results/test-search-results.js
  jujugui/static/gui/src/app/components/search-results/type-filter/test-type-filter.js
Labels: devops

#3609 Update the remaining tests to use Enzyme
  jujugui/static/gui/src/app/components/sharing/sharing.js
  jujugui/static/gui/src/app/components/sharing/test-sharing.js
  jujugui/static/gui/src/app/components/spinner/test-spinner.js
  jujugui/static/gui/src/app/components/status/test-status.js
  jujugui/static/gui/src/app/components/string-config/input/test-input.js
  jujugui/static/gui/src/app/components/string-config/test-string-config.js
  jujugui/static/gui/src/app/components/svg-icon/test-svg-icon.js
  jujugui/static/gui/src/app/components/terminal/terminal.js
  jujugui/static/gui/src/app/components/terminal/test-terminal.js
  jujugui/static/gui/src/app/components/terms-popup/terms-popup.js
  jujugui/static/gui/src/app/components/terms-popup/test-terms-popup.js
  jujugui/static/gui/src/app/components/user-menu/test-user-menu.js
  jujugui/static/gui/src/app/components/user-menu/user-menu.js
  jujugui/static/gui/src/app/components/usso-login-link/test-usso-login-link.js
  jujugui/static/gui/src/app/components/zoom/test-zoom.js
Labels: devops

#3610 Remove redundant test utils
  jujugui/static/gui/src/app/components/deployment-flow/section/test-section.js
  jujugui/static/gui/src/app/utils/component-test-utils.js
  karma.conf.js.tmpl
  package-lock.json
  package.json
Labels: devops

#3612 Hide the change cloud button if there is only one cloud
  jujugui/static/gui/src/app/components/deployment-flow/cloud/cloud.js
  jujugui/static/gui/src/app/components/deployment-flow/cloud/test-cloud.js
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
Labels: QA: OK, enhancement

#3615 The owner is no longer special and not a requirement to being able to delete a model
  jujugui/static/gui/src/app/store/env/acl.js
Labels: enhancement
