Repository juju/juju-gui, pull requests merged in 2018-09, with the labels that each got.

#3781 Update ProfileHeader to use Snapshot testing
  jujugui/static/gui/src/app/components/profile/header/__snapshots__/test-header.js.snap
  jujugui/static/gui/src/app/components/profile/header/test-header.js
Labels: enhancement

#3784 Send analytics ping when exporting bundle.
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/init/hotkeys.js
  jujugui/static/gui/src/app/init/utils.js
  package-lock.json
Labels: enhancement

#3786 Group applications by bundle in the inspector
  jujugui/static/gui/src/app/components/added-services-list/__snapshots__/test-added-services-list.js.snap
  jujugui/static/gui/src/app/components/added-services-list/_added-services-list.scss
  jujugui/static/gui/src/app/components/added-services-list/added-services-list.js
  jujugui/static/gui/src/app/components/added-services-list/item/item.js
  jujugui/static/gui/src/app/components/added-services-list/label/__snapshots__/test-label.js.snap
  jujugui/static/gui/src/app/components/added-services-list/label/label.js
  jujugui/static/gui/src/app/components/added-services-list/label/test-label.js
  jujugui/static/gui/src/app/components/added-services-list/test-added-services-list.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  package-lock.json
Labels: feature

#3787 Update ProfileNavigation to Vanilla v1 markup
  .eslintrc
  jujugui/static/gui/src/app/components/profile/__snapshots__/test-profile.js.snap
  jujugui/static/gui/src/app/components/profile/header/header.js
  jujugui/static/gui/src/app/components/profile/header/test-header.js
  jujugui/static/gui/src/app/components/profile/navigation/__snapshots__/test-navigation.js.snap
  jujugui/static/gui/src/app/components/profile/navigation/_navigation.scss
  jujugui/static/gui/src/app/components/profile/navigation/navigation.js
  jujugui/static/gui/src/app/components/profile/navigation/test-navigation.js
  jujugui/static/gui/src/app/components/profile/profile.js
  jujugui/static/gui/src/app/components/profile/test-profile.js
Labels: QA: OK

#3791 Post Deployment component now correctly updates and handles no-get-started gracefully
  jujugui/static/gui/src/app/components/post-deployment/_post-deployment.scss
  jujugui/static/gui/src/app/components/post-deployment/post-deployment.js
  jujugui/static/gui/src/app/components/post-deployment/test-post-deployment.js
Labels: enhancement

#3790 Shared status components
  jujugui/static/gui/src/app/assets/css/_components.scss
  jujugui/static/gui/src/app/components/shared/status/application-list/__snapshots__/test-application-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/application-list/application-list.js
  jujugui/static/gui/src/app/components/shared/status/application-list/test-application-list.js
  jujugui/static/gui/src/app/components/shared/status/label/__snapshots__/test-label.js.snap
  jujugui/static/gui/src/app/components/shared/status/label/_label.scss
  jujugui/static/gui/src/app/components/shared/status/label/label.js
  jujugui/static/gui/src/app/components/shared/status/label/test-label.js
  jujugui/static/gui/src/app/components/shared/status/machine-list/__snapshots__/test-machine-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/machine-list/machine-list.js
  jujugui/static/gui/src/app/components/shared/status/machine-list/test-machine-list.js
  jujugui/static/gui/src/app/components/shared/status/relation-list/__snapshots__/test-relation-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/relation-list/relation-list.js
  jujugui/static/gui/src/app/components/shared/status/relation-list/test-relation-list.js
  jujugui/static/gui/src/app/components/shared/status/remote-application-list/__snapshots__/test-remote-application-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/remote-application-list/remote-application-list.js
  jujugui/static/gui/src/app/components/shared/status/remote-application-list/test-remote-application-list.js
  jujugui/static/gui/src/app/components/shared/status/table/__snapshots__/test-table.js.snap
  jujugui/static/gui/src/app/components/shared/status/table/_table.scss
  jujugui/static/gui/src/app/components/shared/status/table/table.js
  jujugui/static/gui/src/app/components/shared/status/table/test-table.js
  jujugui/static/gui/src/app/components/shared/status/unit-list/__snapshots__/test-unit-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/unit-list/test-unit-list.js
  jujugui/static/gui/src/app/components/shared/status/unit-list/unit-list.js
  jujugui/static/gui/src/app/components/shared/test-utils.js
  jujugui/static/gui/src/app/components/shared/utils.js
  jujugui/static/gui/src/app/components/status/__snapshots__/test-status.js.snap
  jujugui/static/gui/src/app/components/status/_status.scss
  jujugui/static/gui/src/app/components/status/status.js
  jujugui/static/gui/src/app/components/status/test-status.js
Labels: QA: OK, Review: Needed

#3775 Render top level components using a containing react component.
  jest.config.js
  jujugui/static/gui/src/app/assets/css/_loading.scss
  jujugui/static/gui/src/app/components/expanding-progress/_expanding-progress.scss
  jujugui/static/gui/src/app/components/inspector/change-version/change-version.js
  jujugui/static/gui/src/app/components/notification-list/notification-list.js
  jujugui/static/gui/src/app/components/notification-list/test-notification-list.js
  jujugui/static/gui/src/app/components/profile/charmstore-login/charmstore-login.js
  jujugui/static/gui/src/app/init.js
  jujugui/static/gui/src/app/init/app.js
  jujugui/static/gui/src/app/init/charmstore-user.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/init/cookie-util.js
  jujugui/static/gui/src/app/init/hotkeys.js
  jujugui/static/gui/src/app/init/test-app.js
  jujugui/static/gui/src/app/init/test-cookie-util.js
  jujugui/static/gui/src/app/init/test-hotkeys.js
  jujugui/static/gui/src/app/init/testing-utils.js
  jujugui/static/gui/src/app/init/utils.js
  jujugui/static/gui/src/app/init/utils/bakery-utils.js
  jujugui/static/gui/src/app/init/utils/test-bakery-utils.js
  jujugui/static/gui/src/app/state/state.js
  jujugui/static/gui/src/app/state/test-state.js
  jujugui/static/gui/src/app/test-init.js
  jujugui/templates/index.html.go
  jujugui/templates/index.html.mako
  karma.conf.js.tmpl
  package-lock.json
Labels: QA: OK

#3792 Shared table component
  jujugui/static/gui/src/app/assets/css/_components.scss
  jujugui/static/gui/src/app/components/budget-table/row/row.js
  jujugui/static/gui/src/app/components/budget-table/row/test-row.js
  jujugui/static/gui/src/app/components/deployment-flow/budget/budget.js
  jujugui/static/gui/src/app/components/deployment-flow/budget/test-budget.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/credential.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/test-credential.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/plan-table/plan-table.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/plan-table/test-plan-table.js
  jujugui/static/gui/src/app/components/deployment-flow/services/services.js
  jujugui/static/gui/src/app/components/deployment-flow/services/test-services.js
  jujugui/static/gui/src/app/components/invoice/invoice.js
  jujugui/static/gui/src/app/components/payment/charges/charges.js
  jujugui/static/gui/src/app/components/payment/charges/test-charges.js
  jujugui/static/gui/src/app/components/payment/details/address/address.js
  jujugui/static/gui/src/app/components/payment/details/address/test-address.js
  jujugui/static/gui/src/app/components/payment/methods/method/method.js
  jujugui/static/gui/src/app/components/payment/methods/methods.js
  jujugui/static/gui/src/app/components/profile/bundle-list/bundle-list.js
  jujugui/static/gui/src/app/components/profile/bundle-list/test-bundle-list.js
  jujugui/static/gui/src/app/components/profile/charm-list/charm-list.js
  jujugui/static/gui/src/app/components/profile/charm-list/test-charm-list.js
  jujugui/static/gui/src/app/components/profile/credential-list/credential-list.js
  jujugui/static/gui/src/app/components/profile/credential-list/test-credential-list.js
  jujugui/static/gui/src/app/components/profile/invoice-list/invoice-list.js
  jujugui/static/gui/src/app/components/profile/invoice-list/test-invoice-list.js
  jujugui/static/gui/src/app/components/profile/model-list/model-list.js
  jujugui/static/gui/src/app/components/profile/model-list/test-model-list.js
  jujugui/static/gui/src/app/components/shared/basic-table/_basic-table.scss
  jujugui/static/gui/src/app/components/shared/basic-table/basic-table.js
  jujugui/static/gui/src/app/components/shared/basic-table/test-basic-table.js
  jujugui/static/gui/src/app/components/shared/expanding-row/_expanding-row.scss
  jujugui/static/gui/src/app/components/shared/expanding-row/expanding-row.js
  jujugui/static/gui/src/app/components/shared/expanding-row/test-expanding-row.js
  jujugui/static/gui/src/app/components/shared/status/application-list/__snapshots__/test-application-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/application-list/application-list.js
  jujugui/static/gui/src/app/components/shared/status/application-list/test-application-list.js
  jujugui/static/gui/src/app/components/shared/status/machine-list/__snapshots__/test-machine-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/machine-list/machine-list.js
  jujugui/static/gui/src/app/components/shared/status/machine-list/test-machine-list.js
  jujugui/static/gui/src/app/components/shared/status/relation-list/__snapshots__/test-relation-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/relation-list/relation-list.js
  jujugui/static/gui/src/app/components/shared/status/remote-application-list/__snapshots__/test-remote-application-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/remote-application-list/remote-application-list.js
  jujugui/static/gui/src/app/components/shared/status/remote-application-list/test-remote-application-list.js
  jujugui/static/gui/src/app/components/shared/status/table/__snapshots__/test-table.js.snap
  jujugui/static/gui/src/app/components/shared/status/table/table.js
  jujugui/static/gui/src/app/components/shared/status/table/test-table.js
  jujugui/static/gui/src/app/components/shared/status/unit-list/__snapshots__/test-unit-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/unit-list/test-unit-list.js
  jujugui/static/gui/src/app/components/shared/status/unit-list/unit-list.js
  jujugui/static/gui/src/app/components/status/__snapshots__/test-status.js.snap
  jujugui/static/gui/src/app/components/status/status.js
Labels: QA: OK

#3798 Hide UI mask on login
  jujugui/static/gui/src/app/init.js
  jujugui/static/gui/src/app/init/topology/test-service.js
  jujugui/static/gui/src/app/test-init.js
Labels: QA: OK, bug

#3799 Fix commit from the canvas with new render system
  jujugui/static/gui/src/app/init.js
  jujugui/static/gui/src/app/init/app.js
  jujugui/static/gui/src/app/init/test-app.js
  jujugui/static/gui/src/app/init/test-utils.js
  jujugui/static/gui/src/app/init/utils.js
  jujugui/static/gui/src/app/models/models.js
  jujugui/static/gui/src/app/state/state.js
  jujugui/static/gui/src/app/store/env/base.js
Labels: QA: Needed, Review: Needed, bug

#3801 Split out row and cell components from the basic table
  jujugui/static/gui/src/app/components/shared/basic-table/__snapshots__/test-basic-table.js.snap
  jujugui/static/gui/src/app/components/shared/basic-table/basic-table.js
  jujugui/static/gui/src/app/components/shared/basic-table/cell/__snapshots__/test-cell.js.snap
  jujugui/static/gui/src/app/components/shared/basic-table/cell/cell.js
  jujugui/static/gui/src/app/components/shared/basic-table/cell/test-cell.js
  jujugui/static/gui/src/app/components/shared/basic-table/row/__snapshots__/test-row.js.snap
  jujugui/static/gui/src/app/components/shared/basic-table/row/row.js
  jujugui/static/gui/src/app/components/shared/basic-table/row/test-row.js
  jujugui/static/gui/src/app/components/shared/basic-table/test-basic-table.js
  jujugui/static/gui/src/app/components/status/__snapshots__/test-status.js.snap
Labels: QA: Needed

#3802 Update the basic table to expand content without ExpandingRow
  jujugui/static/gui/src/app/components/deployment-flow/credential/add/add.js
  jujugui/static/gui/src/app/components/shared/basic-table/_basic-table.scss
  jujugui/static/gui/src/app/components/shared/basic-table/row/__snapshots__/test-row.js.snap
  jujugui/static/gui/src/app/components/shared/basic-table/row/row.js
  jujugui/static/gui/src/app/components/shared/basic-table/row/test-row.js
Labels: QA: Needed

#3803 Remove status beta notice
  jujugui/static/gui/src/app/assets/css/_beta.scss
  jujugui/static/gui/src/app/assets/css/_mobile.scss
  jujugui/static/gui/src/app/assets/css/_tablet.scss
  jujugui/static/gui/src/app/assets/css/base.scss
  jujugui/static/gui/src/app/components/status/status.js
  jujugui/static/gui/src/app/init.js
Labels: QA: Needed

#3809 Deploy with pay flag but no pay
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
  jujugui/static/gui/src/app/init.js
Labels: QA: OK

#3808 Parse megawatcher response
  jest.config.js
  jujugui/static/gui/src/app/init.js
  jujugui/static/gui/src/app/init/environment-change-set.js
  jujugui/static/gui/src/app/maraca/maraca.js
  jujugui/static/gui/src/app/maraca/parsers.js
  jujugui/static/gui/src/app/maraca/test-maraca.js
  jujugui/static/gui/src/app/maraca/test-parsers.js
  jujugui/static/gui/src/app/test-init.js
  package-lock.json
  package.json
Labels: QA: OK

#3812 If a charm cannot be found in the charm store, do not fail when trying to read it from the endpoints map.
  jujugui/static/gui/src/app/init/endpoint-utils.js
Labels: QA: OK, bug

#3816 Shared panel component
  jujugui/static/gui/src/app/assets/css/_components.scss
  jujugui/static/gui/src/app/components/charmbrowser/charmbrowser.js
  jujugui/static/gui/src/app/components/deployment-flow/panel/panel.js
  jujugui/static/gui/src/app/components/dropdown-menu/dropdown-menu.js
  jujugui/static/gui/src/app/components/env-switcher/list/list.js
  jujugui/static/gui/src/app/components/isv-profile/isv-profile.js
  jujugui/static/gui/src/app/components/popup/popup.js
  jujugui/static/gui/src/app/components/post-deployment/post-deployment.js
  jujugui/static/gui/src/app/components/profile/profile.js
  jujugui/static/gui/src/app/components/shared/panel/_panel.scss
  jujugui/static/gui/src/app/components/shared/panel/panel.js
  jujugui/static/gui/src/app/components/shared/panel/test-panel.js
  jujugui/static/gui/src/app/components/shared/status/status/status.js
  jujugui/static/gui/src/app/init/app.js
  package-lock.json
Labels: QA: OK

#3818 Pass the icon util into the status components
  jujugui/static/gui/src/app/components/shared/status/application-list/__snapshots__/test-application-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/application-list/application-list.js
  jujugui/static/gui/src/app/components/shared/status/application-list/test-application-list.js
  jujugui/static/gui/src/app/components/shared/status/relation-list/__snapshots__/test-relation-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/relation-list/relation-list.js
  jujugui/static/gui/src/app/components/shared/status/relation-list/test-relation-list.js
  jujugui/static/gui/src/app/components/shared/status/status/__snapshots__/test-status.js.snap
  jujugui/static/gui/src/app/components/shared/status/status/status.js
  jujugui/static/gui/src/app/components/shared/status/status/test-status.js
  jujugui/static/gui/src/app/components/shared/status/unit-list/__snapshots__/test-unit-list.js.snap
  jujugui/static/gui/src/app/components/shared/status/unit-list/test-unit-list.js
  jujugui/static/gui/src/app/components/shared/status/unit-list/unit-list.js
  jujugui/static/gui/src/app/components/status/status.js
  jujugui/static/gui/src/app/init/test-app.js
Labels: QA: OK

#3821 Ensure IP address can display correctly on Profile page
  jujugui/static/gui/src/app/components/profile/header/__snapshots__/test-header.js.snap
  jujugui/static/gui/src/app/components/profile/header/_header.scss
  jujugui/static/gui/src/app/components/profile/header/header.js
Labels: QA: OK
