Repository juju/juju-gui, pull requests merged in 2018-04, with the labels that each got.

#3611 Only show the experts UI when the flag is set.
  jujugui/static/gui/src/app/components/charmbrowser/charmbrowser.js
  jujugui/static/gui/src/app/components/charmbrowser/test-charmbrowser.js
  jujugui/static/gui/src/app/components/store/store.js
  jujugui/static/gui/src/app/components/store/test-store.js
Labels: enhancement

#3619 Create an ExpertBlock component
  jujugui/static/gui/src/app/assets/css/_components.scss
  jujugui/static/gui/src/app/components/expert-block/_expert-block.scss
  jujugui/static/gui/src/app/components/expert-block/expert-block.js
  jujugui/static/gui/src/app/components/expert-block/test-expert-block.js
  jujugui/static/gui/src/app/components/expert-card/_expert-card.scss
  jujugui/static/gui/src/app/components/expert-card/expert-card.js
  jujugui/static/gui/src/app/components/expert-card/test-expert-card.js
  jujugui/static/gui/src/test/chai-setup.js
Labels: QA: OK, enhancement

#3618 Add Invoice component to Profile
  jujugui/static/gui/src/app/assets/css/_components.scss
  jujugui/static/gui/src/app/assets/css/base.scss
  jujugui/static/gui/src/app/components/invoice/_invoice.scss
  jujugui/static/gui/src/app/components/invoice/invoice.js
  jujugui/static/gui/src/app/components/invoice/invoice.test.js
  jujugui/static/gui/src/app/components/profile/invoice-list/invoice-list.js
  jujugui/static/gui/src/app/components/profile/profile.js
  jujugui/static/gui/src/app/components/profile/test-profile.js
Labels: QA: OK

#3620 Add expert flow pricing components
  jujugui/static/gui/src/app/assets/css/_components.scss
  jujugui/static/gui/src/app/assets/css/base.scss
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/_pricing.scss
  jujugui/static/gui/src/app/components/deployment-flow/pricing/plan-table/_plan-table.scss
  jujugui/static/gui/src/app/components/deployment-flow/pricing/plan-table/plan-table.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/plan-table/test-plan-table.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/pricing.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/support-selection/_support-selection.scss
  jujugui/static/gui/src/app/components/deployment-flow/pricing/support-selection/plan/_plan.scss
  jujugui/static/gui/src/app/components/deployment-flow/pricing/support-selection/plan/plan.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/support-selection/plan/test-plan.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/support-selection/support-selection.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/support-selection/test-support-selection.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/test-pricing.js
  jujugui/static/gui/src/app/components/profile/bundle-list/_bundle-list.scss
Labels: QA: OK, enhancement

#3617 Static build of Revenue statement UI
  jujugui/static/gui/src/app/assets/css/_components.scss
  jujugui/static/gui/src/app/assets/css/base.scss
  jujugui/static/gui/src/app/components/profile/profile.js
  jujugui/static/gui/src/app/components/revenue-statement/_revenue-statement.scss
  jujugui/static/gui/src/app/components/revenue-statement/revenue-statement.js
  jujugui/static/gui/src/app/components/revenue-statement/test-revenue-statement.js
Labels: QA: OK

#3623 Add Rates api to Jujulib
  development.ini
  jujugui/options.py
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
  jujugui/static/gui/src/app/init.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/jujulib/index.js
  jujugui/static/gui/src/app/jujulib/rates.js
  jujugui/static/gui/src/app/jujulib/test-rates.js
  jujugui/templates/config.js.go
  jujugui/tests/test_options.py
  jujugui/views.py
  karma.conf.js.tmpl
Labels: feature

#3622 Add basic budget component for the expert flow
  jujugui/static/gui/src/app/assets/css/_components.scss
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-budget/_expert-budget.scss
  jujugui/static/gui/src/app/components/deployment-flow/expert-budget/expert-budget.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-budget/test-expert-budget.js
  jujugui/static/gui/src/app/components/generic-input/_generic-input.scss
  jujugui/static/gui/src/app/components/generic-input/generic-input.js
  jujugui/static/gui/src/app/components/notification/_notification.scss
  jujugui/static/gui/src/app/components/notification/notification.js
Labels: QA: OK, enhancement

#3625 Add expert flow intro
  jujugui/static/gui/src/app/assets/css/_components.scss
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/_expert-intro.scss
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/expert-intro.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/test-expert-intro.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
  jujugui/static/gui/src/app/components/expert-store-card/expert-store-card.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK, enhancement

#3627 Put some real data in the expert intro
  jujugui/static/gui/src/app/components/deployment-flow/direct-deploy/direct-deploy.js
  jujugui/static/gui/src/app/components/deployment-flow/direct-deploy/test-direct-deploy.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/_expert-intro.scss
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/expert-intro.js
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/test-expert-intro.js
  jujugui/static/gui/src/app/components/entity-details/content/content.js
  jujugui/static/gui/src/app/components/entity-details/content/description/description.js
  jujugui/static/gui/src/app/components/entity-details/content/description/test-description.js
  jujugui/static/gui/src/app/components/entity-details/content/test-content.js
Labels: QA: OK, enhancement

#3628 Clear the canvas when switching from new model to new model
  jujugui/static/gui/src/app/init/test-utils.js
  jujugui/static/gui/src/app/init/utils.js
Labels: QA: OK, bug

#3629 Hook up rates api
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/pricing.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/support-selection/support-selection.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/support-selection/test-support-selection.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/test-pricing.js
Labels: QA: OK, enhancement

#3630 Connect plans table
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/plan-table/_plan-table.scss
  jujugui/static/gui/src/app/components/deployment-flow/pricing/plan-table/plan-table.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/plan-table/test-plan-table.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/pricing.js
  jujugui/static/gui/src/app/components/deployment-flow/pricing/test-pricing.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/jujulib/plans.js
  jujugui/static/gui/src/app/jujulib/test-plans.js
Labels: QA: OK, enhancement

#3631 Setup expert flow
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
  jujugui/static/gui/src/app/jujulib/charmstore.js
  jujugui/static/gui/src/app/jujulib/test-charmstore.js
Labels: QA: OK, enhancement

#3633 Expand experts
  jujugui/static/gui/src/app/assets/images/non-sprites/experts/tengu.png
  jujugui/static/gui/src/app/components/expert-card/experts.js
  jujugui/static/gui/src/app/components/expert-card/test-expert-card.js
  jujugui/static/gui/src/app/components/expert-contact-card/test-expert-contact-card.js
  jujugui/static/gui/src/app/components/expert-store-card/test-expert-store-card.js
  karma-mocha-old.conf.js.tmpl
Labels: enhancement

#3634 Update handling of pip download
  Makefile
Labels: QA: OK, bug, devops

#3635 Update deps
  jujugui/static/gui/src/app/init.js
  jujugui/static/gui/src/app/init/test-zip-utils.js
  jujugui/static/gui/src/app/test-init.js
  package-lock.json
  package.json
Labels: QA: Needed, Review: Needed, devops
