Repository juju/juju-gui, pull requests merged in 2018-07, with the labels that each got.

#3736 Fix promise race condition for the CI
  jujugui/static/gui/src/app/init/test-endpoint-utils.js
Labels: blocker, bug

#3729 Updated jaaslib to 0.4.0.
  package-lock.json
  package.json
Labels: QA: OK, enhancement

#3727 Post deployment panel shapes
  jujugui/static/gui/src/app/components/post-deployment/post-deployment.js
  jujugui/static/gui/src/app/components/post-deployment/test-post-deployment.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK

#3738 Lock the xterm versions
  package.json
Labels: blocker, bug

#3731 Remove syntax highlighting
  jujugui/static/gui/src/app/assets/css/base.scss
  jujugui/static/gui/src/app/assets/css/plugins/prism.scss
  jujugui/static/gui/src/app/components/entity-details/content/readme/readme.js
  package-lock.json
  package.json
Labels: QA: OK

#3741 Surface errors when deleting models
  jujugui/static/gui/src/app/components/profile/model-list/model-list.js
  jujugui/static/gui/src/app/components/profile/model-list/test-model-list.js
  jujugui/static/gui/src/app/init/utils.js
  jujugui/static/gui/src/app/store/env/controller-api.js
  jujugui/static/gui/src/test/test_controller_api.js
Labels: QA: OK

#3743 Update to use new bakery
  jujugui/static/gui/src/app/init/utils/bakery-utils.js
  jujugui/static/gui/src/app/init/utils/test-bakery-utils.js
  package-lock.json
  package.json
Labels: QA: OK, enhancement

#3745 Add Travis CI support
  .travis.yml
Labels: devops

#3744 Disable machine view for k8s
  jujugui/static/gui/src/app/components/env-size-display/env-size-display.js
  jujugui/static/gui/src/app/components/env-size-display/test-env-size-display.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK, enhancement

#3740 Shared machine component
  jujugui/static/gui/src/app/assets/css/_components.scss
  jujugui/static/gui/src/app/components/machine-view/machine-unit/_machine-unit.scss
  jujugui/static/gui/src/app/components/machine-view/machine-unit/machine-unit.js
  jujugui/static/gui/src/app/components/machine-view/machine-unit/test-machine-unit.js
  jujugui/static/gui/src/app/components/machine-view/machine-view.js
  jujugui/static/gui/src/app/components/machine-view/machine/_machine.scss
  jujugui/static/gui/src/app/components/machine-view/machine/machine.js
  jujugui/static/gui/src/app/components/machine-view/machine/test-machine.js
  jujugui/static/gui/src/app/components/machine-view/test-machine-view.js
  jujugui/static/gui/src/app/components/shared/machine-unit/_machine-unit.scss
  jujugui/static/gui/src/app/components/shared/machine-unit/machine-unit.js
  jujugui/static/gui/src/app/components/shared/machine-unit/test-machine-unit.js
  jujugui/static/gui/src/app/components/shared/machine/_machine.scss
  jujugui/static/gui/src/app/components/shared/machine/machine.js
  jujugui/static/gui/src/app/components/shared/machine/test-machine.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/init/test-utils.js
  jujugui/static/gui/src/app/init/utils.js
Labels: QA: OK

#3748 Implement new unit view
  jujugui/static/gui/src/app/components/inspector/inspector.js
  jujugui/static/gui/src/app/components/inspector/test-inspector.js
  jujugui/static/gui/src/app/components/inspector/unit-details/_unit-details.scss
  jujugui/static/gui/src/app/components/inspector/unit-details/test-unit-details.js
  jujugui/static/gui/src/app/components/inspector/unit-details/unit-details.js
Labels: QA: OK, Review: Needed

#3750 Include the version file in the dist
  MANIFEST.in
  jujugui/templates/index.html.go
  jujugui/templates/index.html.mako
Labels: QA: OK, bug

#3749 Show correct constraints details when not set
  jujugui/static/gui/src/app/init/test-utils.js
  jujugui/static/gui/src/app/init/utils.js
Labels: QA: OK, bug

#3752 Fix unit details prop error
  jujugui/static/gui/src/app/components/inspector/unit-details/test-unit-details.js
  jujugui/static/gui/src/app/components/inspector/unit-details/unit-details.js
Labels: QA: OK

#3751 Added services shapes and cleanup
  jujugui/static/gui/src/app/components/added-services-list/added-services-list.js
  jujugui/static/gui/src/app/components/added-services-list/item/item.js
  jujugui/static/gui/src/app/components/added-services-list/item/test-item.js
  jujugui/static/gui/src/app/components/added-services-list/test-added-services-list.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK

#3758 Fix cancelling payment address forms
  jujugui/static/gui/src/app/components/payment/details/details.js
Labels: QA: Needed, Review: Needed, bug
