Repository juju/juju-gui, pull requests merged in 2018-08, with the labels that each got.

#3762 Bundle export module
  jujugui/static/gui/src/app/init/bundle-exporter.js
  jujugui/static/gui/src/app/init/test-bundle-exporter.js
  jujugui/static/gui/src/app/init/test-utils.js
  jujugui/static/gui/src/app/init/utils.js
  jujugui/static/gui/src/app/models/models.js
  jujugui/static/gui/src/app/models/test-models.js
Labels: QA: OK

#3763 Update normalize.css
  jujugui/static/gui/src/app/components/header-search/_header-search.scss
  package-lock.json
  package.json
Labels: QA: OK

#3766 Prevent addMachine and deploy callbacks from breaking deployments
  jujugui/static/gui/src/app/extensions/yui-patches.js
  jujugui/static/gui/src/app/init/autodeploy.js
  jujugui/static/gui/src/app/init/deployer-mixin.js
  jujugui/static/gui/src/app/init/test-deployer-mixin.js
  jujugui/static/gui/src/app/yui-modules.js
  jujugui/static/gui/src/test/globalconfig.js
  jujugui/templates/index.html.go
  jujugui/templates/index.html.mako
Labels: QA: OK, blocker, bug, high priority

#3764 Remove link colour override
  jujugui/static/gui/src/app/assets/css/_mixins.scss
  jujugui/static/gui/src/app/assets/css/base.scss
  jujugui/static/gui/src/app/assets/css/canvas/_relation-menu.scss
  jujugui/static/gui/src/app/components/deployment-flow/expert-intro/_expert-intro.scss
  jujugui/static/gui/src/app/components/deployment-flow/login/_login.scss
  jujugui/static/gui/src/app/components/deployment-flow/pricing/_pricing.scss
  jujugui/static/gui/src/app/components/dropdown-menu/_dropdown-menu.scss
  jujugui/static/gui/src/app/components/entity-details/content/_content.scss
  jujugui/static/gui/src/app/components/entity-details/content/content.js
  jujugui/static/gui/src/app/components/entity-details/content/files/files.js
  jujugui/static/gui/src/app/components/entity-details/content/files/test-files.js
  jujugui/static/gui/src/app/components/entity-details/content/test-content.js
  jujugui/static/gui/src/app/components/env-size-display/_env-size-display.scss
  jujugui/static/gui/src/app/components/header-breadcrumb/_header-breadcrumb.scss
  jujugui/static/gui/src/app/components/inspector/header/_header.scss
  jujugui/static/gui/src/app/components/notification/_notification.scss
  jujugui/static/gui/src/app/components/profile/expanded-content/_expanded-content.scss
  jujugui/static/gui/src/app/components/profile/header/_header.scss
  jujugui/static/gui/src/app/components/store/_store.scss
  jujugui/static/gui/src/app/components/store/store.js
  jujugui/static/gui/src/app/components/store/test-store.js
Labels: QA: OK

#3769 Work around the destroy storage error
  jujugui/static/gui/src/app/components/profile/model-list/model-list.js
  jujugui/static/gui/src/app/store/env/controller-api.js
  jujugui/static/gui/src/test/test_controller_api.js
Labels: QA: OK

#3783 Reduce snapshot sizes
  jest.config.js
  jujugui/static/gui/src/app/components/help/__snapshots__/test-help.js.snap
  package-lock.json
  package.json
Labels: Review: Needed

#3782 Fix post deployment so that it shows even if the bundle is modified.
  jujugui/static/gui/src/app/components/entity-details/header/header.js
  jujugui/static/gui/src/app/components/inspector/header/header.js
  jujugui/static/gui/src/app/components/inspector/header/test-header.js
  jujugui/static/gui/src/app/components/post-deployment/post-deployment.js
  jujugui/static/gui/src/app/components/post-deployment/test-post-deployment.js
  jujugui/static/gui/src/app/components/search-results/item/item.js
  jujugui/static/gui/src/app/init.js
  jujugui/static/gui/src/app/init/bundle-importer.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
  jujugui/static/gui/src/app/init/test-utils.js
  jujugui/static/gui/src/app/init/utils.js
Labels: QA: OK, bug
