Repository juju/juju-gui, pull requests merged in 2018-02, with the labels that each got.

#3492 Close profile on model-list model click.
  jujugui/static/gui/src/app/components/profile/model-list/model-list.js
  jujugui/static/gui/src/app/components/profile/model-list/test-model-list.js
Labels: QA: OK, bug

#3504 Fix credential help spacing
  jujugui/static/gui/src/app/components/deployment-flow/_deployment-flow.scss
  jujugui/static/gui/src/app/components/deployment-flow/credential/add/_add.scss
  jujugui/static/gui/src/app/components/deployment-flow/credential/add/add.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/add/test-add.js
Labels: QA: Needed, bug

#3505 Fix credential file updating
  jujugui/static/gui/src/app/components/file-field/file-field.js
  jujugui/static/gui/src/app/components/profile/credential-list/credential-list.js
  jujugui/static/gui/src/app/components/profile/credential-list/test-credential-list.js
Labels: bug

#3511 Do not hide the third item, which is now the logout link, in the user menu
  jujugui/static/gui/src/app/components/user-menu/_user-menu.scss
Labels: QA: OK, bug

#3509 Only call the cleanup methods for existing state keys.
  jujugui/static/gui/src/app/init.js
  jujugui/static/gui/src/app/state/state.js
  jujugui/static/gui/src/app/state/test-state.js
Labels: enhancement

#3506 Login to the charmstore from the profile
  jujugui/static/gui/src/app/assets/css/_components.scss
  jujugui/static/gui/src/app/components/profile/bundle-list/_bundle-list.scss
  jujugui/static/gui/src/app/components/profile/bundle-list/bundle-list.js
  jujugui/static/gui/src/app/components/profile/bundle-list/test-bundle-list.js
  jujugui/static/gui/src/app/components/profile/charm-list/charm-list.js
  jujugui/static/gui/src/app/components/profile/charm-list/test-charm-list.js
  jujugui/static/gui/src/app/components/profile/charmstore-login/_charmstore-login.scss
  jujugui/static/gui/src/app/components/profile/charmstore-login/charmstore-login.js
  jujugui/static/gui/src/app/components/profile/charmstore-login/test-charmstore-login.js
  jujugui/static/gui/src/app/components/profile/profile.js
  jujugui/static/gui/src/app/components/profile/test-profile.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: QA: OK, enhancement

#3524 Make login and store links work
  jujugui/static/gui/src/app/components/profile/charmstore-login/charmstore-login.js
  jujugui/static/gui/src/app/components/profile/charmstore-login/test-charmstore-login.js
Labels: bug

#3523 Clear the add credential form when reopened
  jujugui/static/gui/src/app/components/profile/credential-list/credential-list.js
  jujugui/static/gui/src/app/components/profile/credential-list/test-credential-list.js
Labels: QA: Bad, QA: Needed, bug

#3529 Do not show all models superusers have access to
  jujugui/static/gui/src/app/components/profile/model-list/model-list.js
  jujugui/static/gui/src/app/components/profile/model-list/test-model-list.js
Labels: QA: OK, bug

#3531 Fix expanded content links
  jujugui/static/gui/src/app/components/link/link.js
  jujugui/static/gui/src/app/components/link/test-link.js
  jujugui/static/gui/src/app/components/profile/bundle-list/bundle-list.js
  jujugui/static/gui/src/app/components/profile/bundle-list/test-bundle-list.js
  jujugui/static/gui/src/app/components/profile/charm-list/charm-list.js
  jujugui/static/gui/src/app/components/profile/charm-list/test-charm-list.js
  jujugui/static/gui/src/app/components/profile/expanded-content/expanded-content.js
  jujugui/static/gui/src/app/components/profile/expanded-content/test-expanded-content.js
  jujugui/static/gui/src/app/components/profile/profile.js
Labels: QA: Needed, Review: Needed, bug

#3532 Fix table rows overlapping
  jujugui/static/gui/src/app/components/basic-table/_basic-table.scss
  jujugui/static/gui/src/app/components/basic-table/basic-table.js
  jujugui/static/gui/src/app/components/basic-table/test-basic-table.js
Labels: QA: Needed, Review: Needed, bug

#3536 Fix the popup background
  jujugui/static/gui/src/app/components/panel/_panel.scss
Labels: bug

#3537 Fix the font size of the expanded profile entity details
  jujugui/static/gui/src/app/components/profile/expanded-content/_expanded-content.scss
Labels: enhancement

#3538 Fix the credentials form so it can be submitted by pressing enter
  jujugui/static/gui/src/app/components/deployment-flow/credential/add/add.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/add/test-add.js
  jujugui/static/gui/src/app/components/profile/credential-list/_credential-list.scss
Labels: bug

#3543 Update the DestroyModels API call for the new Juju API
  jujugui/static/gui/src/app/store/env/controller-api.js
  jujugui/static/gui/src/test/test_controller_api.js
Labels: QA: OK, blocker, bug

#3542 jujushell: handle possible initial welcome message.
  jujugui/static/gui/src/app/components/terminal/terminal.js
  jujugui/static/gui/src/app/components/terminal/test-terminal.js
Labels: enhancement

#3539 Only show the controller info on the current user's profile
  jujugui/static/gui/src/app/components/profile/header/header.js
  jujugui/static/gui/src/app/components/profile/header/test-header.js
  jujugui/static/gui/src/app/components/profile/profile.js
  jujugui/static/gui/src/app/components/profile/test-profile.js
  jujugui/static/gui/src/app/init/component-renderers-mixin.js
Labels: enhancement

#3550 Don't show the inspector scaling screen when read only
  jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js
  jujugui/static/gui/src/app/components/inspector/unit-list/unit-list.js
Labels: enhancement

#3545 Fix the spinner when loading entity details
  jujugui/static/gui/src/app/components/entity-details/_entity-details.scss
Labels: QA: OK, bug

#3547 Display a commit button when committing
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
Labels: QA: OK, enhancement

#3553 Fix tour buttons
  jujugui/static/gui/src/app/components/lightbox/_lightbox.scss
  jujugui/static/gui/src/app/components/lightbox/lightbox.js
  jujugui/static/gui/src/app/components/lightbox/test-lightbox.js
Labels: QA: OK, bug

#3555 Disable add keys button after adding GitHub keys
  jujugui/static/gui/src/app/components/deployment-flow/sshkey/sshkey.js
  jujugui/static/gui/src/app/components/deployment-flow/sshkey/test-sshkey.js
Labels: QA: OK, enhancement

#3554 Don't show a signup url for MAAS
  jujugui/static/gui/src/app/components/deployment-flow/credential/add/add.js
  jujugui/static/gui/src/app/components/deployment-flow/credential/add/test-add.js
Labels: QA: Needed, Review: Needed, bug

#3546 Fix inspector header height
  jujugui/static/gui/src/app/components/inspector/header/_header.scss
Labels: QA: OK, bug

#3563 Re-enable the deploy button if deploying fails
  jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js
  jujugui/static/gui/src/app/components/deployment-flow/test-deployment-flow.js
Labels: QA: OK, enhancement
