Repository juju/juju-gui, pull requests merged in 2019-05, with the labels that each got.

#3943 Require protocol be defined in JAAS_API_BASE in the gui config view.
  .env
  webapp/blueprint.py
Labels: QA: OK

#3950 Add static routes to redirect to jaas.ai
  webapp/blueprint.py
Labels: QA: OK

#3953 Handle root docs path redirect.
  webapp/blueprint.py
Labels: QA: OK

#3951 Cloud icon profile changes
  Makefile
  gui/src/app/components/env-switcher/list/__snapshots__/test-list.js.snap
  gui/src/app/components/env-switcher/list/_list.scss
  gui/src/app/components/env-switcher/list/list.js
  gui/src/app/components/env-switcher/list/test-list.js
  gui/src/app/components/profile/model-list/__snapshots__/test-model-list.js.snap
  gui/src/app/components/profile/model-list/_model-list.scss
  gui/src/app/components/profile/model-list/model-list.js
  gui/src/app/components/profile/model-list/test-model-list.js
  package.json
  static/assets/svgs/profile-aws.svg
  static/assets/svgs/profile-azure.svg
  static/assets/svgs/profile-google.svg
  static/gui/build/app/assets/stack/svg/sprite.css.svg
Labels: QA: OK

#3954 Fix logout
  gui/src/app/init.js
Labels: Review: Code needed, Review: QA needed

#3956 Fix profile context menu icon
  static/assets/svgs/contextual-menu-horizontal.svg
  static/gui/build/app/assets/stack/svg/sprite.css.svg
Labels: QA: OK

#3967 Remove old Google Analytics events
  gui/src/app/components/charmbrowser/charmbrowser.js
  gui/src/app/components/charmbrowser/test-charmbrowser.js
  gui/src/app/components/credential-add-edit/credential-add-edit.js
  gui/src/app/components/credential-add-edit/test-credential-add-edit.js
  gui/src/app/components/deployment-bar/deployment-bar.js
  gui/src/app/components/deployment-bar/test-deployment-bar.js
  gui/src/app/components/deployment-flow/credential/add/add.js
  gui/src/app/components/deployment-flow/credential/add/test-add.js
  gui/src/app/components/deployment-flow/credential/credential.js
  gui/src/app/components/deployment-flow/credential/test-credential.js
  gui/src/app/components/deployment-flow/deployment-flow.js
  gui/src/app/components/deployment-flow/expert-intro/__snapshots__/test-expert-intro.js.snap
  gui/src/app/components/deployment-flow/expert-intro/expert-intro.js
  gui/src/app/components/deployment-flow/expert-intro/test-expert-intro.js
  gui/src/app/components/deployment-flow/panel/panel.js
  gui/src/app/components/deployment-flow/panel/test-panel.js
  gui/src/app/components/deployment-flow/test-deployment-flow.js
  gui/src/app/components/entity-details/content/__snapshots__/test-content.js.snap
  gui/src/app/components/entity-details/content/content.js
  gui/src/app/components/entity-details/content/test-content.js
  gui/src/app/components/entity-details/entity-details.js
  gui/src/app/components/entity-details/test-entity-details.js
  gui/src/app/components/expert-contact-card/expert-contact-card.js
  gui/src/app/components/expert-contact-card/test-expert-contact-card.js
  gui/src/app/components/machine-view/column/column.js
  gui/src/app/components/machine-view/column/test-column.js
  gui/src/app/components/machine-view/header/header.js
  gui/src/app/components/machine-view/header/test-header.js
  gui/src/app/components/machine-view/machine-unit/machine-unit.js
  gui/src/app/components/machine-view/machine-unit/test-machine-unit.js
  gui/src/app/components/machine-view/machine-view.js
  gui/src/app/components/machine-view/machine/machine.js
  gui/src/app/components/machine-view/machine/test-machine.js
  gui/src/app/components/machine-view/test-machine-view.js
  gui/src/app/components/machine-view/unplaced-unit/test-unplaced-unit.js
  gui/src/app/components/machine-view/unplaced-unit/unplaced-unit.js
  gui/src/app/components/profile/credential-list/__snapshots__/test-credential-list.js.snap
  gui/src/app/components/profile/credential-list/credential-list.js
  gui/src/app/components/profile/credential-list/test-credential-list.js
  gui/src/app/components/profile/profile.js
  gui/src/app/components/profile/test-profile.js
  gui/src/app/init.js
  gui/src/app/init/app.js
  gui/src/app/init/hotkeys.js
  gui/src/app/init/test-app.js
  gui/src/app/init/topology/environment.js
  gui/src/app/init/topology/test-environment.js
  gui/src/app/init/utils.js
  gui/src/app/models/models.js
  gui/src/app/models/test-models.js
  gui/src/app/state/state.js
  gui/src/app/state/test-state.js
Labels: QA: OK

#3969 Add component analytics collection/sending
  gui/src/app/components/charmbrowser/__snapshots__/test-charmbrowser.js.snap
  gui/src/app/components/charmbrowser/charmbrowser.js
  gui/src/app/components/charmbrowser/test-charmbrowser.js
  gui/src/app/components/inspector/__snapshots__/test-inspector.js.snap
  gui/src/app/components/inspector/config/config.js
  gui/src/app/components/inspector/config/test-config.js
  gui/src/app/components/inspector/inspector.js
  gui/src/app/components/inspector/test-inspector.js
  gui/src/app/components/inspector/unit-details/test-unit-details.js
  gui/src/app/components/inspector/unit-details/unit-details.js
  gui/src/app/components/search-results/__snapshots__/test-search-results.js.snap
  gui/src/app/components/search-results/search-results.js
  gui/src/app/components/search-results/select-filter/select-filter.js
  gui/src/app/components/search-results/select-filter/test-select-filter.js
  gui/src/app/components/search-results/test-search-results.js
  gui/src/app/init.js
  gui/src/app/init/analytics.js
  gui/src/app/init/app.js
  gui/src/app/init/test-analytics.js
  gui/src/app/init/topology/environment.js
  gui/src/app/init/topology/test-environment.js
  gui/src/app/state/state.js
  jest.config.js
  karma.conf.js.tmpl
Labels: QA: Needed, Review: Needed

#3968 Fix tooltip messaging format for add-to-model button.
  gui/src/app/components/entity-details/header/__snapshots__/test-header.js.snap
  gui/src/app/components/entity-details/header/header.js
Labels: QA: OK

#3970 Enable tag manager
  templates/config.js.jinja
  templates/index.html
  webapp/blueprint.py
Labels: Review: Code needed, Review: QA needed

#3971 Add analytics to the header
  gui/src/app/components/charmbrowser/__snapshots__/test-charmbrowser.js.snap
  gui/src/app/components/charmbrowser/test-charmbrowser.js
  gui/src/app/components/create-model-button/create-model-button.js
  gui/src/app/components/create-model-button/test-create-model-button.js
  gui/src/app/components/env-switcher/env-switcher.js
  gui/src/app/components/env-switcher/list/__snapshots__/test-list.js.snap
  gui/src/app/components/env-switcher/list/list.js
  gui/src/app/components/env-switcher/list/test-list.js
  gui/src/app/components/env-switcher/test-env-switcher.js
  gui/src/app/components/header-breadcrumb/__snapshots__/test-header-breadcrumb.js.snap
  gui/src/app/components/header-breadcrumb/header-breadcrumb.js
  gui/src/app/components/header-breadcrumb/test-header-breadcrumb.js
  gui/src/app/components/header-search/header-search.js
  gui/src/app/components/header-search/test-header-search.js
  gui/src/app/components/help/help.js
  gui/src/app/components/help/test-help.js
  gui/src/app/components/inspector/__snapshots__/test-inspector.js.snap
  gui/src/app/components/inspector/config/config.js
  gui/src/app/components/inspector/config/test-config.js
  gui/src/app/components/inspector/test-inspector.js
  gui/src/app/components/inspector/unit-details/test-unit-details.js
  gui/src/app/components/logout/logout.js
  gui/src/app/components/logout/test-logout.js
  gui/src/app/components/model-actions/model-actions.js
  gui/src/app/components/model-actions/test-model-actions.js
  gui/src/app/components/search-results/__snapshots__/test-search-results.js.snap
  gui/src/app/components/search-results/select-filter/test-select-filter.js
  gui/src/app/components/search-results/test-search-results.js
  gui/src/app/components/user-menu/test-user-menu.js
  gui/src/app/components/user-menu/user-menu.js
  gui/src/app/components/usso-login-link/test-usso-login-link.js
  gui/src/app/components/usso-login-link/usso-login-link.js
  gui/src/app/init.js
  gui/src/app/init/app.js
  gui/src/app/init/test-app.js
  gui/src/app/init/topology/test-environment.js
  gui/src/test/fake-analytics.js
Labels: Review: QA needed

#3972 Add profile analytics
  gui/src/app/components/credential-add-edit/__snapshots__/test-credential-add-edit.js.snap
  gui/src/app/components/credential-add-edit/credential-add-edit.js
  gui/src/app/components/credential-add-edit/test-credential-add-edit.js
  gui/src/app/components/deployment-flow/__snapshots__/test-deployment-flow.js.snap
  gui/src/app/components/deployment-flow/cloud/cloud.js
  gui/src/app/components/deployment-flow/cloud/test-cloud.js
  gui/src/app/components/deployment-flow/credential/__snapshots__/test-credential.js.snap
  gui/src/app/components/deployment-flow/credential/add/add.js
  gui/src/app/components/deployment-flow/credential/add/test-add.js
  gui/src/app/components/deployment-flow/credential/credential.js
  gui/src/app/components/deployment-flow/credential/test-credential.js
  gui/src/app/components/deployment-flow/deployment-flow.js
  gui/src/app/components/deployment-flow/test-deployment-flow.js
  gui/src/app/components/profile/__snapshots__/test-profile.js.snap
  gui/src/app/components/profile/bundle-list/bundle-list.js
  gui/src/app/components/profile/bundle-list/test-bundle-list.js
  gui/src/app/components/profile/charm-list/charm-list.js
  gui/src/app/components/profile/charm-list/test-charm-list.js
  gui/src/app/components/profile/credential-list/__snapshots__/test-credential-list.js.snap
  gui/src/app/components/profile/credential-list/credential-list.js
  gui/src/app/components/profile/credential-list/test-credential-list.js
  gui/src/app/components/profile/header/header.js
  gui/src/app/components/profile/header/test-header.js
  gui/src/app/components/profile/model-list/__snapshots__/test-model-list.js.snap
  gui/src/app/components/profile/model-list/model-list.js
  gui/src/app/components/profile/model-list/test-model-list.js
  gui/src/app/components/profile/profile.js
  gui/src/app/components/profile/test-profile.js
  gui/src/app/init.js
  gui/src/app/init/analytics.js
  gui/src/app/init/app.js
Labels: QA: OK

#3976 Add analytics to the status
  gui/src/app/components/status/status.js
  gui/src/app/components/status/test-status.js
  gui/src/app/init/app.js
Labels: QA: OK

#3973 Add canvas analytics
  gui/src/app/init/analytics.js
  gui/src/app/init/topology/environment.js
  gui/src/app/init/topology/relation.js
  gui/src/app/init/topology/service.js
  gui/src/app/init/topology/topology.js
Labels: QA: OK

#3978 Add inspector analytics
  gui/src/app/components/inspector/__snapshots__/test-inspector.js.snap
  gui/src/app/components/inspector/change-version/change-version.js
  gui/src/app/components/inspector/change-version/test-change-version.js
  gui/src/app/components/inspector/expose/expose.js
  gui/src/app/components/inspector/expose/test-expose.js
  gui/src/app/components/inspector/header/header.js
  gui/src/app/components/inspector/header/test-header.js
  gui/src/app/components/inspector/inspector.js
  gui/src/app/components/inspector/plan/plan.js
  gui/src/app/components/inspector/plan/test-plan.js
  gui/src/app/components/inspector/relate-to/endpoint/endpoint.js
  gui/src/app/components/inspector/relate-to/endpoint/test-endpoint.js
  gui/src/app/components/inspector/relate-to/relate-to.js
  gui/src/app/components/inspector/relate-to/test-relate-to.js
  gui/src/app/components/inspector/relations/details/details.js
  gui/src/app/components/inspector/relations/details/test-details.js
  gui/src/app/components/inspector/relations/relations.js
  gui/src/app/components/inspector/relations/test-relations.js
  gui/src/app/components/inspector/resources/list/list.js
  gui/src/app/components/inspector/resources/list/test-list.js
  gui/src/app/components/inspector/scale-service/scale-service.js
  gui/src/app/components/inspector/scale-service/test-scale-service.js
  gui/src/app/components/inspector/service-overview/service-overview.js
  gui/src/app/components/inspector/service-overview/test-service-overview.js
  gui/src/app/components/inspector/test-inspector.js
  gui/src/app/components/inspector/unit-details/unit-details.js
  gui/src/app/components/inspector/unit-list/test-unit-list.js
  gui/src/app/components/inspector/unit-list/unit-list.js
  gui/src/app/components/local-inspector/local-inspector.js
  gui/src/app/components/local-inspector/test-local-inspector.js
  gui/src/app/init/analytics.js
  gui/src/app/init/app.js
  gui/src/app/init/relation-utils.js
Labels: QA: OK

#3975 Add analytics to the store
  gui/src/app/components/charmbrowser/__snapshots__/test-charmbrowser.js.snap
  gui/src/app/components/charmbrowser/charmbrowser.js
  gui/src/app/components/copy-to-clipboard/__snapshots__/test-copy-to-clipboard.js.snap
  gui/src/app/components/copy-to-clipboard/copy-to-clipboard.js
  gui/src/app/components/copy-to-clipboard/test-copy-to-clipboard.js
  gui/src/app/components/entity-details/__snapshots__/test-entity-details.js.snap
  gui/src/app/components/entity-details/content/__snapshots__/test-content.js.snap
  gui/src/app/components/entity-details/content/content.js
  gui/src/app/components/entity-details/content/relations/relations.js
  gui/src/app/components/entity-details/content/relations/test-relations.js
  gui/src/app/components/entity-details/content/resources/test-resources.js
  gui/src/app/components/entity-details/content/test-content.js
  gui/src/app/components/entity-details/entity-details.js
  gui/src/app/components/entity-details/header/__snapshots__/test-header.js.snap
  gui/src/app/components/entity-details/header/header.js
  gui/src/app/components/entity-details/header/test-header.js
  gui/src/app/components/entity-details/test-entity-details.js
  gui/src/app/components/expert-contact-card/expert-contact-card.js
  gui/src/app/components/expert-contact-card/test-expert-contact-card.js
  gui/src/app/components/search-results/__snapshots__/test-search-results.js.snap
  gui/src/app/components/search-results/item/item.js
  gui/src/app/components/search-results/item/test-item.js
  gui/src/app/components/search-results/search-results.js
  gui/src/app/components/search-results/test-search-results.js
  gui/src/app/components/search-results/type-filter/test-type-filter.js
  gui/src/app/components/search-results/type-filter/type-filter.js
  gui/src/app/components/store/store.js
  gui/src/app/components/store/test-store.js
Labels: QA: OK

#3977 Add machine view analytics
  gui/src/app/components/machine-view/__snapshots__/test-machine-view.js.snap
  gui/src/app/components/machine-view/add-machine/add-machine.js
  gui/src/app/components/machine-view/add-machine/test-add-machine.js
  gui/src/app/components/machine-view/column/__snapshots__/test-column.js.snap
  gui/src/app/components/machine-view/column/column.js
  gui/src/app/components/machine-view/column/test-column.js
  gui/src/app/components/machine-view/header/header.js
  gui/src/app/components/machine-view/header/test-header.js
  gui/src/app/components/machine-view/machine-unit/machine-unit.js
  gui/src/app/components/machine-view/machine-unit/test-machine-unit.js
  gui/src/app/components/machine-view/machine-view.js
  gui/src/app/components/machine-view/machine/__snapshots__/test-machine.js.snap
  gui/src/app/components/machine-view/machine/machine.js
  gui/src/app/components/machine-view/machine/test-machine.js
  gui/src/app/components/machine-view/scale-up/scale-up.js
  gui/src/app/components/machine-view/scale-up/test-scale-up.js
  gui/src/app/components/machine-view/test-machine-view.js
  gui/src/app/components/machine-view/unplaced-unit/test-unplaced-unit.js
  gui/src/app/components/machine-view/unplaced-unit/unplaced-unit.js
  gui/src/app/init/analytics.js
  gui/src/app/init/app.js
Labels: QA: OK

#3979 Add analytics to the deployment flow
  gui/src/app/components/deployment-bar/__snapshots__/test-deployment-bar.js.snap
  gui/src/app/components/deployment-bar/deployment-bar.js
  gui/src/app/components/deployment-bar/notification/notification.js
  gui/src/app/components/deployment-bar/notification/test-notification.js
  gui/src/app/components/deployment-bar/test-deployment-bar.js
  gui/src/app/components/deployment-flow/__snapshots__/test-deployment-flow.js.snap
  gui/src/app/components/deployment-flow/agreements/__snapshots__/test-agreements.js.snap
  gui/src/app/components/deployment-flow/agreements/agreements.js
  gui/src/app/components/deployment-flow/agreements/test-agreements.js
  gui/src/app/components/deployment-flow/budget/budget.js
  gui/src/app/components/deployment-flow/budget/test-budget.js
  gui/src/app/components/deployment-flow/cloud/cloud.js
  gui/src/app/components/deployment-flow/credential/add/add.js
  gui/src/app/components/deployment-flow/credential/credential.js
  gui/src/app/components/deployment-flow/deployment-flow.js
  gui/src/app/components/deployment-flow/direct-deploy/direct-deploy.js
  gui/src/app/components/deployment-flow/direct-deploy/test-direct-deploy.js
  gui/src/app/components/deployment-flow/expert-budget/expert-budget.js
  gui/src/app/components/deployment-flow/expert-budget/test-expert-budget.js
  gui/src/app/components/deployment-flow/expert-intro/__snapshots__/test-expert-intro.js.snap
  gui/src/app/components/deployment-flow/expert-intro/expert-intro.js
  gui/src/app/components/deployment-flow/expert-intro/test-expert-intro.js
  gui/src/app/components/deployment-flow/login/__snapshots__/test-login.js.snap
  gui/src/app/components/deployment-flow/login/login.js
  gui/src/app/components/deployment-flow/login/test-login.js
  gui/src/app/components/deployment-flow/model-name/model-name.js
  gui/src/app/components/deployment-flow/model-name/test-model-name.js
  gui/src/app/components/deployment-flow/panel/panel.js
  gui/src/app/components/deployment-flow/panel/test-panel.js
  gui/src/app/components/deployment-flow/pricing/__snapshots__/test-pricing.js.snap
  gui/src/app/components/deployment-flow/pricing/pricing.js
  gui/src/app/components/deployment-flow/pricing/support-selection/__snapshots__/test-support-selection.js.snap
  gui/src/app/components/deployment-flow/pricing/support-selection/plan/__snapshots__/test-plan.js.snap
  gui/src/app/components/deployment-flow/pricing/support-selection/plan/plan.js
  gui/src/app/components/deployment-flow/pricing/support-selection/plan/test-plan.js
  gui/src/app/components/deployment-flow/pricing/support-selection/support-selection.js
  gui/src/app/components/deployment-flow/pricing/support-selection/test-support-selection.js
  gui/src/app/components/deployment-flow/pricing/test-pricing.js
  gui/src/app/components/deployment-flow/sshkey/sshkey.js
  gui/src/app/components/deployment-flow/sshkey/test-sshkey.js
  gui/src/app/components/deployment-flow/test-deployment-flow.js
  gui/src/app/components/deployment-flow/vpc/test-vpc.js
  gui/src/app/components/deployment-flow/vpc/vpc.js
  gui/src/app/components/payment/payment.js
  gui/src/app/components/payment/test-payment.js
  gui/src/app/init/analytics.js
  gui/src/app/init/app.js
Labels: QA: OK

#3983 Fix analytics events
  gui/src/app/components/accordion-section/accordion-section.js
  gui/src/app/components/deployment-flow/__snapshots__/test-deployment-flow.js.snap
  gui/src/app/components/deployment-flow/deployment-flow.js
  gui/src/app/components/deployment-flow/direct-deploy/direct-deploy.js
  gui/src/app/components/login/__snapshots__/test-login.js.snap
  gui/src/app/components/login/login.js
  gui/src/app/components/login/test-login.js
  gui/src/app/components/post-deployment/post-deployment.js
  gui/src/app/components/post-deployment/test-post-deployment.js
  gui/src/app/components/usso-login-link/usso-login-link.js
  gui/src/app/init.js
  gui/src/app/init/analytics.js
  gui/src/app/init/app.js
Labels: QA: OK

#3987 Fix adding credentials
  gui/src/app/components/deployment-flow/credential/add/add.js
  gui/src/app/components/deployment-flow/credential/add/test-add.js
  gui/src/app/components/inspector/scale-service/scale-service.js
  gui/src/app/components/profile/credential-list/_credential-list.scss
Labels: QA: OK

#3989 Update series list
  gui/src/app/assets/css/plugins/cloud-vanilla-theme/scss/modules/_forms.scss
  gui/src/app/components/search-results/__snapshots__/test-search-results.js.snap
  gui/src/app/components/series-list/__snapshots__/test-series-list.js.snap
  gui/src/app/components/series-list/series-list.js
  gui/src/app/init/utils.js
Labels: QA: OK

#3991 Remove old notification analytics event
  gui/src/app/components/notification-list/notification-list.js
Labels: QA: OK
